/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsNewRouteImport } from './routes/events/new'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as EventsEventIdVolunteersRouteImport } from './routes/events/$eventId/volunteers'
import { Route as EventsEventIdStaffingRouteImport } from './routes/events/$eventId/staffing'
import { Route as EventsEventIdShiftsRouteImport } from './routes/events/$eventId/shifts'
import { Route as EventsEventIdSetupRouteImport } from './routes/events/$eventId/setup'
import { Route as EventsEventIdScheduleRouteImport } from './routes/events/$eventId/schedule'
import { Route as EventsEventIdReadinessRouteImport } from './routes/events/$eventId/readiness'
import { Route as EventsEventIdJudgesRouteImport } from './routes/events/$eventId/judges'
import { Route as EventsEventIdImportsRouteImport } from './routes/events/$eventId/imports'
import { Route as EventsEventIdExportsRouteImport } from './routes/events/$eventId/exports'
import { Route as EventsEventIdDayOfRouteImport } from './routes/events/$eventId/day-of'
import { Route as EventsEventIdBillingRouteImport } from './routes/events/$eventId/billing'
import { Route as ESlugVolunteerRouteImport } from './routes/e/$slug/volunteer'
import { Route as ApiCrewImportRouteImport } from './routes/api/crew/import'
import { Route as ESlugScheduleTokenRouteImport } from './routes/e/$slug/schedule/$token'
import { Route as ESlugConfirmTokenRouteImport } from './routes/e/$slug/confirm/$token'

const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EventsRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdVolunteersRoute = EventsEventIdVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdStaffingRoute = EventsEventIdStaffingRouteImport.update({
  id: '/staffing',
  path: '/staffing',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdShiftsRoute = EventsEventIdShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdSetupRoute = EventsEventIdSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdScheduleRoute = EventsEventIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdReadinessRoute = EventsEventIdReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdJudgesRoute = EventsEventIdJudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdImportsRoute = EventsEventIdImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdExportsRoute = EventsEventIdExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdDayOfRoute = EventsEventIdDayOfRouteImport.update({
  id: '/day-of',
  path: '/day-of',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdBillingRoute = EventsEventIdBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const ESlugVolunteerRoute = ESlugVolunteerRouteImport.update({
  id: '/e/$slug/volunteer',
  path: '/e/$slug/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrewImportRoute = ApiCrewImportRouteImport.update({
  id: '/api/crew/import',
  path: '/api/crew/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugScheduleTokenRoute = ESlugScheduleTokenRouteImport.update({
  id: '/e/$slug/schedule/$token',
  path: '/e/$slug/schedule/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugConfirmTokenRoute = ESlugConfirmTokenRouteImport.update({
  id: '/e/$slug/confirm/$token',
  path: '/e/$slug/confirm/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/events': typeof EventsRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/api/crew/import': typeof ApiCrewImportRoute
  '/e/$slug/volunteer': typeof ESlugVolunteerRoute
  '/events/$eventId/billing': typeof EventsEventIdBillingRoute
  '/events/$eventId/day-of': typeof EventsEventIdDayOfRoute
  '/events/$eventId/exports': typeof EventsEventIdExportsRoute
  '/events/$eventId/imports': typeof EventsEventIdImportsRoute
  '/events/$eventId/judges': typeof EventsEventIdJudgesRoute
  '/events/$eventId/readiness': typeof EventsEventIdReadinessRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
  '/events/$eventId/setup': typeof EventsEventIdSetupRoute
  '/events/$eventId/shifts': typeof EventsEventIdShiftsRoute
  '/events/$eventId/staffing': typeof EventsEventIdStaffingRoute
  '/events/$eventId/volunteers': typeof EventsEventIdVolunteersRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/e/$slug/confirm/$token': typeof ESlugConfirmTokenRoute
  '/e/$slug/schedule/$token': typeof ESlugScheduleTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/events': typeof EventsRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/api/crew/import': typeof ApiCrewImportRoute
  '/e/$slug/volunteer': typeof ESlugVolunteerRoute
  '/events/$eventId/billing': typeof EventsEventIdBillingRoute
  '/events/$eventId/day-of': typeof EventsEventIdDayOfRoute
  '/events/$eventId/exports': typeof EventsEventIdExportsRoute
  '/events/$eventId/imports': typeof EventsEventIdImportsRoute
  '/events/$eventId/judges': typeof EventsEventIdJudgesRoute
  '/events/$eventId/readiness': typeof EventsEventIdReadinessRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
  '/events/$eventId/setup': typeof EventsEventIdSetupRoute
  '/events/$eventId/shifts': typeof EventsEventIdShiftsRoute
  '/events/$eventId/staffing': typeof EventsEventIdStaffingRoute
  '/events/$eventId/volunteers': typeof EventsEventIdVolunteersRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/e/$slug/confirm/$token': typeof ESlugConfirmTokenRoute
  '/e/$slug/schedule/$token': typeof ESlugScheduleTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/events': typeof EventsRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/api/crew/import': typeof ApiCrewImportRoute
  '/e/$slug/volunteer': typeof ESlugVolunteerRoute
  '/events/$eventId/billing': typeof EventsEventIdBillingRoute
  '/events/$eventId/day-of': typeof EventsEventIdDayOfRoute
  '/events/$eventId/exports': typeof EventsEventIdExportsRoute
  '/events/$eventId/imports': typeof EventsEventIdImportsRoute
  '/events/$eventId/judges': typeof EventsEventIdJudgesRoute
  '/events/$eventId/readiness': typeof EventsEventIdReadinessRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
  '/events/$eventId/setup': typeof EventsEventIdSetupRoute
  '/events/$eventId/shifts': typeof EventsEventIdShiftsRoute
  '/events/$eventId/staffing': typeof EventsEventIdStaffingRoute
  '/events/$eventId/volunteers': typeof EventsEventIdVolunteersRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/e/$slug/confirm/$token': typeof ESlugConfirmTokenRoute
  '/e/$slug/schedule/$token': typeof ESlugScheduleTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/events'
    | '/events/$eventId'
    | '/events/new'
    | '/api/crew/import'
    | '/e/$slug/volunteer'
    | '/events/$eventId/billing'
    | '/events/$eventId/day-of'
    | '/events/$eventId/exports'
    | '/events/$eventId/imports'
    | '/events/$eventId/judges'
    | '/events/$eventId/readiness'
    | '/events/$eventId/schedule'
    | '/events/$eventId/setup'
    | '/events/$eventId/shifts'
    | '/events/$eventId/staffing'
    | '/events/$eventId/volunteers'
    | '/events/$eventId/'
    | '/e/$slug/confirm/$token'
    | '/e/$slug/schedule/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/events'
    | '/events/new'
    | '/api/crew/import'
    | '/e/$slug/volunteer'
    | '/events/$eventId/billing'
    | '/events/$eventId/day-of'
    | '/events/$eventId/exports'
    | '/events/$eventId/imports'
    | '/events/$eventId/judges'
    | '/events/$eventId/readiness'
    | '/events/$eventId/schedule'
    | '/events/$eventId/setup'
    | '/events/$eventId/shifts'
    | '/events/$eventId/staffing'
    | '/events/$eventId/volunteers'
    | '/events/$eventId'
    | '/e/$slug/confirm/$token'
    | '/e/$slug/schedule/$token'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/events'
    | '/events/$eventId'
    | '/events/new'
    | '/api/crew/import'
    | '/e/$slug/volunteer'
    | '/events/$eventId/billing'
    | '/events/$eventId/day-of'
    | '/events/$eventId/exports'
    | '/events/$eventId/imports'
    | '/events/$eventId/judges'
    | '/events/$eventId/readiness'
    | '/events/$eventId/schedule'
    | '/events/$eventId/setup'
    | '/events/$eventId/shifts'
    | '/events/$eventId/staffing'
    | '/events/$eventId/volunteers'
    | '/events/$eventId/'
    | '/e/$slug/confirm/$token'
    | '/e/$slug/schedule/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  EventsRoute: typeof EventsRouteWithChildren
  ApiCrewImportRoute: typeof ApiCrewImportRoute
  ESlugVolunteerRoute: typeof ESlugVolunteerRoute
  ESlugConfirmTokenRoute: typeof ESlugConfirmTokenRoute
  ESlugScheduleTokenRoute: typeof ESlugScheduleTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/volunteers': {
      id: '/events/$eventId/volunteers'
      path: '/volunteers'
      fullPath: '/events/$eventId/volunteers'
      preLoaderRoute: typeof EventsEventIdVolunteersRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/staffing': {
      id: '/events/$eventId/staffing'
      path: '/staffing'
      fullPath: '/events/$eventId/staffing'
      preLoaderRoute: typeof EventsEventIdStaffingRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/shifts': {
      id: '/events/$eventId/shifts'
      path: '/shifts'
      fullPath: '/events/$eventId/shifts'
      preLoaderRoute: typeof EventsEventIdShiftsRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/setup': {
      id: '/events/$eventId/setup'
      path: '/setup'
      fullPath: '/events/$eventId/setup'
      preLoaderRoute: typeof EventsEventIdSetupRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/schedule': {
      id: '/events/$eventId/schedule'
      path: '/schedule'
      fullPath: '/events/$eventId/schedule'
      preLoaderRoute: typeof EventsEventIdScheduleRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/readiness': {
      id: '/events/$eventId/readiness'
      path: '/readiness'
      fullPath: '/events/$eventId/readiness'
      preLoaderRoute: typeof EventsEventIdReadinessRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/judges': {
      id: '/events/$eventId/judges'
      path: '/judges'
      fullPath: '/events/$eventId/judges'
      preLoaderRoute: typeof EventsEventIdJudgesRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/imports': {
      id: '/events/$eventId/imports'
      path: '/imports'
      fullPath: '/events/$eventId/imports'
      preLoaderRoute: typeof EventsEventIdImportsRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/exports': {
      id: '/events/$eventId/exports'
      path: '/exports'
      fullPath: '/events/$eventId/exports'
      preLoaderRoute: typeof EventsEventIdExportsRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/day-of': {
      id: '/events/$eventId/day-of'
      path: '/day-of'
      fullPath: '/events/$eventId/day-of'
      preLoaderRoute: typeof EventsEventIdDayOfRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/billing': {
      id: '/events/$eventId/billing'
      path: '/billing'
      fullPath: '/events/$eventId/billing'
      preLoaderRoute: typeof EventsEventIdBillingRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/e/$slug/volunteer': {
      id: '/e/$slug/volunteer'
      path: '/e/$slug/volunteer'
      fullPath: '/e/$slug/volunteer'
      preLoaderRoute: typeof ESlugVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crew/import': {
      id: '/api/crew/import'
      path: '/api/crew/import'
      fullPath: '/api/crew/import'
      preLoaderRoute: typeof ApiCrewImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug/schedule/$token': {
      id: '/e/$slug/schedule/$token'
      path: '/e/$slug/schedule/$token'
      fullPath: '/e/$slug/schedule/$token'
      preLoaderRoute: typeof ESlugScheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug/confirm/$token': {
      id: '/e/$slug/confirm/$token'
      path: '/e/$slug/confirm/$token'
      fullPath: '/e/$slug/confirm/$token'
      preLoaderRoute: typeof ESlugConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsEventIdRouteChildren {
  EventsEventIdBillingRoute: typeof EventsEventIdBillingRoute
  EventsEventIdDayOfRoute: typeof EventsEventIdDayOfRoute
  EventsEventIdExportsRoute: typeof EventsEventIdExportsRoute
  EventsEventIdImportsRoute: typeof EventsEventIdImportsRoute
  EventsEventIdJudgesRoute: typeof EventsEventIdJudgesRoute
  EventsEventIdReadinessRoute: typeof EventsEventIdReadinessRoute
  EventsEventIdScheduleRoute: typeof EventsEventIdScheduleRoute
  EventsEventIdSetupRoute: typeof EventsEventIdSetupRoute
  EventsEventIdShiftsRoute: typeof EventsEventIdShiftsRoute
  EventsEventIdStaffingRoute: typeof EventsEventIdStaffingRoute
  EventsEventIdVolunteersRoute: typeof EventsEventIdVolunteersRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdBillingRoute: EventsEventIdBillingRoute,
  EventsEventIdDayOfRoute: EventsEventIdDayOfRoute,
  EventsEventIdExportsRoute: EventsEventIdExportsRoute,
  EventsEventIdImportsRoute: EventsEventIdImportsRoute,
  EventsEventIdJudgesRoute: EventsEventIdJudgesRoute,
  EventsEventIdReadinessRoute: EventsEventIdReadinessRoute,
  EventsEventIdScheduleRoute: EventsEventIdScheduleRoute,
  EventsEventIdSetupRoute: EventsEventIdSetupRoute,
  EventsEventIdShiftsRoute: EventsEventIdShiftsRoute,
  EventsEventIdStaffingRoute: EventsEventIdStaffingRoute,
  EventsEventIdVolunteersRoute: EventsEventIdVolunteersRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
  EventsNewRoute: typeof EventsNewRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
  EventsNewRoute: EventsNewRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  EventsRoute: EventsRouteWithChildren,
  ApiCrewImportRoute: ApiCrewImportRoute,
  ESlugVolunteerRoute: ESlugVolunteerRoute,
  ESlugConfirmTokenRoute: ESlugConfirmTokenRoute,
  ESlugScheduleTokenRoute: ESlugScheduleTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
