/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsNewRouteImport } from './routes/events/new'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as AdminCrewRouteImport } from './routes/admin/crew'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as SeriesGroupIdCrewRouteImport } from './routes/series/$groupId/crew'
import { Route as EventsEventIdVolunteersRouteImport } from './routes/events/$eventId/volunteers'
import { Route as EventsEventIdStaffingRouteImport } from './routes/events/$eventId/staffing'
import { Route as EventsEventIdShiftsRouteImport } from './routes/events/$eventId/shifts'
import { Route as EventsEventIdSetupRouteImport } from './routes/events/$eventId/setup'
import { Route as EventsEventIdScheduleRouteImport } from './routes/events/$eventId/schedule'
import { Route as EventsEventIdReadinessRouteImport } from './routes/events/$eventId/readiness'
import { Route as EventsEventIdMessagesRouteImport } from './routes/events/$eventId/messages'
import { Route as EventsEventIdJudgesRouteImport } from './routes/events/$eventId/judges'
import { Route as EventsEventIdHeatsRouteImport } from './routes/events/$eventId/heats'
import { Route as EventsEventIdExportsRouteImport } from './routes/events/$eventId/exports'
import { Route as EventsEventIdDayOfRouteImport } from './routes/events/$eventId/day-of'
import { Route as EventsEventIdConvertRouteImport } from './routes/events/$eventId/convert'
import { Route as EventsEventIdBillingRouteImport } from './routes/events/$eventId/billing'
import { Route as ESlugVolunteerRouteImport } from './routes/e/$slug/volunteer'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiE2eSessionRouteImport } from './routes/api/e2e/session'
import { Route as ApiCrewImportRouteImport } from './routes/api/crew/import'
import { Route as AdminCrewEventsRouteImport } from './routes/admin/crew/events'
import { Route as EventsEventIdDiscoveryJudgesRouteImport } from './routes/events/$eventId/discovery/judges'
import { Route as ESlugScheduleTokenRouteImport } from './routes/e/$slug/schedule/$token'
import { Route as ESlugConsentTokenRouteImport } from './routes/e/$slug/consent/$token'
import { Route as ESlugConfirmTokenRouteImport } from './routes/e/$slug/confirm/$token'
import { Route as AdminCrewEventsEventIdRouteImport } from './routes/admin/crew/events/$eventId'
import { Route as AdminCrewEventsEventIdReadinessRouteImport } from './routes/admin/crew/events/$eventId/readiness'
import { Route as AdminCrewEventsEventIdConvertRouteImport } from './routes/admin/crew/events/$eventId/convert'
import { Route as AdminCrewEventsEventIdBillingRouteImport } from './routes/admin/crew/events/$eventId/billing'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EventsRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const AdminCrewRoute = AdminCrewRouteImport.update({
  id: '/admin/crew',
  path: '/admin/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const SeriesGroupIdCrewRoute = SeriesGroupIdCrewRouteImport.update({
  id: '/series/$groupId/crew',
  path: '/series/$groupId/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdVolunteersRoute = EventsEventIdVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdStaffingRoute = EventsEventIdStaffingRouteImport.update({
  id: '/staffing',
  path: '/staffing',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdShiftsRoute = EventsEventIdShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdSetupRoute = EventsEventIdSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdScheduleRoute = EventsEventIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdReadinessRoute = EventsEventIdReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdMessagesRoute = EventsEventIdMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdJudgesRoute = EventsEventIdJudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdHeatsRoute = EventsEventIdHeatsRouteImport.update({
  id: '/heats',
  path: '/heats',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdExportsRoute = EventsEventIdExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdDayOfRoute = EventsEventIdDayOfRouteImport.update({
  id: '/day-of',
  path: '/day-of',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdConvertRoute = EventsEventIdConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdBillingRoute = EventsEventIdBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const ESlugVolunteerRoute = ESlugVolunteerRouteImport.update({
  id: '/e/$slug/volunteer',
  path: '/e/$slug/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiE2eSessionRoute = ApiE2eSessionRouteImport.update({
  id: '/api/e2e/session',
  path: '/api/e2e/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrewImportRoute = ApiCrewImportRouteImport.update({
  id: '/api/crew/import',
  path: '/api/crew/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrewEventsRoute = AdminCrewEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminCrewRoute,
} as any)
const EventsEventIdDiscoveryJudgesRoute =
  EventsEventIdDiscoveryJudgesRouteImport.update({
    id: '/discovery/judges',
    path: '/discovery/judges',
    getParentRoute: () => EventsEventIdRoute,
  } as any)
const ESlugScheduleTokenRoute = ESlugScheduleTokenRouteImport.update({
  id: '/e/$slug/schedule/$token',
  path: '/e/$slug/schedule/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugConsentTokenRoute = ESlugConsentTokenRouteImport.update({
  id: '/e/$slug/consent/$token',
  path: '/e/$slug/consent/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugConfirmTokenRoute = ESlugConfirmTokenRouteImport.update({
  id: '/e/$slug/confirm/$token',
  path: '/e/$slug/confirm/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrewEventsEventIdRoute = AdminCrewEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AdminCrewEventsRoute,
} as any)
const AdminCrewEventsEventIdReadinessRoute =
  AdminCrewEventsEventIdReadinessRouteImport.update({
    id: '/readiness',
    path: '/readiness',
    getParentRoute: () => AdminCrewEventsEventIdRoute,
  } as any)
const AdminCrewEventsEventIdConvertRoute =
  AdminCrewEventsEventIdConvertRouteImport.update({
    id: '/convert',
    path: '/convert',
    getParentRoute: () => AdminCrewEventsEventIdRoute,
  } as any)
const AdminCrewEventsEventIdBillingRoute =
  AdminCrewEventsEventIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AdminCrewEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/events': typeof EventsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/crew': typeof AdminCrewRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/admin/crew/events': typeof AdminCrewEventsRouteWithChildren
  '/api/crew/import': typeof ApiCrewImportRoute
  '/api/e2e/session': typeof ApiE2eSessionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/e/$slug/volunteer': typeof ESlugVolunteerRoute
  '/events/$eventId/billing': typeof EventsEventIdBillingRoute
  '/events/$eventId/convert': typeof EventsEventIdConvertRoute
  '/events/$eventId/day-of': typeof EventsEventIdDayOfRoute
  '/events/$eventId/exports': typeof EventsEventIdExportsRoute
  '/events/$eventId/heats': typeof EventsEventIdHeatsRoute
  '/events/$eventId/judges': typeof EventsEventIdJudgesRoute
  '/events/$eventId/messages': typeof EventsEventIdMessagesRoute
  '/events/$eventId/readiness': typeof EventsEventIdReadinessRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
  '/events/$eventId/setup': typeof EventsEventIdSetupRoute
  '/events/$eventId/shifts': typeof EventsEventIdShiftsRoute
  '/events/$eventId/staffing': typeof EventsEventIdStaffingRoute
  '/events/$eventId/volunteers': typeof EventsEventIdVolunteersRoute
  '/series/$groupId/crew': typeof SeriesGroupIdCrewRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/admin/crew/events/$eventId': typeof AdminCrewEventsEventIdRouteWithChildren
  '/e/$slug/confirm/$token': typeof ESlugConfirmTokenRoute
  '/e/$slug/consent/$token': typeof ESlugConsentTokenRoute
  '/e/$slug/schedule/$token': typeof ESlugScheduleTokenRoute
  '/events/$eventId/discovery/judges': typeof EventsEventIdDiscoveryJudgesRoute
  '/admin/crew/events/$eventId/billing': typeof AdminCrewEventsEventIdBillingRoute
  '/admin/crew/events/$eventId/convert': typeof AdminCrewEventsEventIdConvertRoute
  '/admin/crew/events/$eventId/readiness': typeof AdminCrewEventsEventIdReadinessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/events': typeof EventsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/crew': typeof AdminCrewRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/admin/crew/events': typeof AdminCrewEventsRouteWithChildren
  '/api/crew/import': typeof ApiCrewImportRoute
  '/api/e2e/session': typeof ApiE2eSessionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/e/$slug/volunteer': typeof ESlugVolunteerRoute
  '/events/$eventId/billing': typeof EventsEventIdBillingRoute
  '/events/$eventId/convert': typeof EventsEventIdConvertRoute
  '/events/$eventId/day-of': typeof EventsEventIdDayOfRoute
  '/events/$eventId/exports': typeof EventsEventIdExportsRoute
  '/events/$eventId/heats': typeof EventsEventIdHeatsRoute
  '/events/$eventId/judges': typeof EventsEventIdJudgesRoute
  '/events/$eventId/messages': typeof EventsEventIdMessagesRoute
  '/events/$eventId/readiness': typeof EventsEventIdReadinessRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
  '/events/$eventId/setup': typeof EventsEventIdSetupRoute
  '/events/$eventId/shifts': typeof EventsEventIdShiftsRoute
  '/events/$eventId/staffing': typeof EventsEventIdStaffingRoute
  '/events/$eventId/volunteers': typeof EventsEventIdVolunteersRoute
  '/series/$groupId/crew': typeof SeriesGroupIdCrewRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/admin/crew/events/$eventId': typeof AdminCrewEventsEventIdRouteWithChildren
  '/e/$slug/confirm/$token': typeof ESlugConfirmTokenRoute
  '/e/$slug/consent/$token': typeof ESlugConsentTokenRoute
  '/e/$slug/schedule/$token': typeof ESlugScheduleTokenRoute
  '/events/$eventId/discovery/judges': typeof EventsEventIdDiscoveryJudgesRoute
  '/admin/crew/events/$eventId/billing': typeof AdminCrewEventsEventIdBillingRoute
  '/admin/crew/events/$eventId/convert': typeof AdminCrewEventsEventIdConvertRoute
  '/admin/crew/events/$eventId/readiness': typeof AdminCrewEventsEventIdReadinessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/events': typeof EventsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/crew': typeof AdminCrewRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/admin/crew/events': typeof AdminCrewEventsRouteWithChildren
  '/api/crew/import': typeof ApiCrewImportRoute
  '/api/e2e/session': typeof ApiE2eSessionRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/e/$slug/volunteer': typeof ESlugVolunteerRoute
  '/events/$eventId/billing': typeof EventsEventIdBillingRoute
  '/events/$eventId/convert': typeof EventsEventIdConvertRoute
  '/events/$eventId/day-of': typeof EventsEventIdDayOfRoute
  '/events/$eventId/exports': typeof EventsEventIdExportsRoute
  '/events/$eventId/heats': typeof EventsEventIdHeatsRoute
  '/events/$eventId/judges': typeof EventsEventIdJudgesRoute
  '/events/$eventId/messages': typeof EventsEventIdMessagesRoute
  '/events/$eventId/readiness': typeof EventsEventIdReadinessRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
  '/events/$eventId/setup': typeof EventsEventIdSetupRoute
  '/events/$eventId/shifts': typeof EventsEventIdShiftsRoute
  '/events/$eventId/staffing': typeof EventsEventIdStaffingRoute
  '/events/$eventId/volunteers': typeof EventsEventIdVolunteersRoute
  '/series/$groupId/crew': typeof SeriesGroupIdCrewRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/admin/crew/events/$eventId': typeof AdminCrewEventsEventIdRouteWithChildren
  '/e/$slug/confirm/$token': typeof ESlugConfirmTokenRoute
  '/e/$slug/consent/$token': typeof ESlugConsentTokenRoute
  '/e/$slug/schedule/$token': typeof ESlugScheduleTokenRoute
  '/events/$eventId/discovery/judges': typeof EventsEventIdDiscoveryJudgesRoute
  '/admin/crew/events/$eventId/billing': typeof AdminCrewEventsEventIdBillingRoute
  '/admin/crew/events/$eventId/convert': typeof AdminCrewEventsEventIdConvertRoute
  '/admin/crew/events/$eventId/readiness': typeof AdminCrewEventsEventIdReadinessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/events'
    | '/sign-in'
    | '/sign-up'
    | '/admin/crew'
    | '/events/$eventId'
    | '/events/new'
    | '/admin/crew/events'
    | '/api/crew/import'
    | '/api/e2e/session'
    | '/api/webhooks/stripe'
    | '/e/$slug/volunteer'
    | '/events/$eventId/billing'
    | '/events/$eventId/convert'
    | '/events/$eventId/day-of'
    | '/events/$eventId/exports'
    | '/events/$eventId/heats'
    | '/events/$eventId/judges'
    | '/events/$eventId/messages'
    | '/events/$eventId/readiness'
    | '/events/$eventId/schedule'
    | '/events/$eventId/setup'
    | '/events/$eventId/shifts'
    | '/events/$eventId/staffing'
    | '/events/$eventId/volunteers'
    | '/series/$groupId/crew'
    | '/events/$eventId/'
    | '/admin/crew/events/$eventId'
    | '/e/$slug/confirm/$token'
    | '/e/$slug/consent/$token'
    | '/e/$slug/schedule/$token'
    | '/events/$eventId/discovery/judges'
    | '/admin/crew/events/$eventId/billing'
    | '/admin/crew/events/$eventId/convert'
    | '/admin/crew/events/$eventId/readiness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/events'
    | '/sign-in'
    | '/sign-up'
    | '/admin/crew'
    | '/events/new'
    | '/admin/crew/events'
    | '/api/crew/import'
    | '/api/e2e/session'
    | '/api/webhooks/stripe'
    | '/e/$slug/volunteer'
    | '/events/$eventId/billing'
    | '/events/$eventId/convert'
    | '/events/$eventId/day-of'
    | '/events/$eventId/exports'
    | '/events/$eventId/heats'
    | '/events/$eventId/judges'
    | '/events/$eventId/messages'
    | '/events/$eventId/readiness'
    | '/events/$eventId/schedule'
    | '/events/$eventId/setup'
    | '/events/$eventId/shifts'
    | '/events/$eventId/staffing'
    | '/events/$eventId/volunteers'
    | '/series/$groupId/crew'
    | '/events/$eventId'
    | '/admin/crew/events/$eventId'
    | '/e/$slug/confirm/$token'
    | '/e/$slug/consent/$token'
    | '/e/$slug/schedule/$token'
    | '/events/$eventId/discovery/judges'
    | '/admin/crew/events/$eventId/billing'
    | '/admin/crew/events/$eventId/convert'
    | '/admin/crew/events/$eventId/readiness'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/events'
    | '/sign-in'
    | '/sign-up'
    | '/admin/crew'
    | '/events/$eventId'
    | '/events/new'
    | '/admin/crew/events'
    | '/api/crew/import'
    | '/api/e2e/session'
    | '/api/webhooks/stripe'
    | '/e/$slug/volunteer'
    | '/events/$eventId/billing'
    | '/events/$eventId/convert'
    | '/events/$eventId/day-of'
    | '/events/$eventId/exports'
    | '/events/$eventId/heats'
    | '/events/$eventId/judges'
    | '/events/$eventId/messages'
    | '/events/$eventId/readiness'
    | '/events/$eventId/schedule'
    | '/events/$eventId/setup'
    | '/events/$eventId/shifts'
    | '/events/$eventId/staffing'
    | '/events/$eventId/volunteers'
    | '/series/$groupId/crew'
    | '/events/$eventId/'
    | '/admin/crew/events/$eventId'
    | '/e/$slug/confirm/$token'
    | '/e/$slug/consent/$token'
    | '/e/$slug/schedule/$token'
    | '/events/$eventId/discovery/judges'
    | '/admin/crew/events/$eventId/billing'
    | '/admin/crew/events/$eventId/convert'
    | '/admin/crew/events/$eventId/readiness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  EventsRoute: typeof EventsRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AdminCrewRoute: typeof AdminCrewRouteWithChildren
  ApiCrewImportRoute: typeof ApiCrewImportRoute
  ApiE2eSessionRoute: typeof ApiE2eSessionRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ESlugVolunteerRoute: typeof ESlugVolunteerRoute
  SeriesGroupIdCrewRoute: typeof SeriesGroupIdCrewRoute
  ESlugConfirmTokenRoute: typeof ESlugConfirmTokenRoute
  ESlugConsentTokenRoute: typeof ESlugConsentTokenRoute
  ESlugScheduleTokenRoute: typeof ESlugScheduleTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/crew': {
      id: '/admin/crew'
      path: '/admin/crew'
      fullPath: '/admin/crew'
      preLoaderRoute: typeof AdminCrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/series/$groupId/crew': {
      id: '/series/$groupId/crew'
      path: '/series/$groupId/crew'
      fullPath: '/series/$groupId/crew'
      preLoaderRoute: typeof SeriesGroupIdCrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/volunteers': {
      id: '/events/$eventId/volunteers'
      path: '/volunteers'
      fullPath: '/events/$eventId/volunteers'
      preLoaderRoute: typeof EventsEventIdVolunteersRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/staffing': {
      id: '/events/$eventId/staffing'
      path: '/staffing'
      fullPath: '/events/$eventId/staffing'
      preLoaderRoute: typeof EventsEventIdStaffingRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/shifts': {
      id: '/events/$eventId/shifts'
      path: '/shifts'
      fullPath: '/events/$eventId/shifts'
      preLoaderRoute: typeof EventsEventIdShiftsRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/setup': {
      id: '/events/$eventId/setup'
      path: '/setup'
      fullPath: '/events/$eventId/setup'
      preLoaderRoute: typeof EventsEventIdSetupRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/schedule': {
      id: '/events/$eventId/schedule'
      path: '/schedule'
      fullPath: '/events/$eventId/schedule'
      preLoaderRoute: typeof EventsEventIdScheduleRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/readiness': {
      id: '/events/$eventId/readiness'
      path: '/readiness'
      fullPath: '/events/$eventId/readiness'
      preLoaderRoute: typeof EventsEventIdReadinessRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/messages': {
      id: '/events/$eventId/messages'
      path: '/messages'
      fullPath: '/events/$eventId/messages'
      preLoaderRoute: typeof EventsEventIdMessagesRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/judges': {
      id: '/events/$eventId/judges'
      path: '/judges'
      fullPath: '/events/$eventId/judges'
      preLoaderRoute: typeof EventsEventIdJudgesRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/heats': {
      id: '/events/$eventId/heats'
      path: '/heats'
      fullPath: '/events/$eventId/heats'
      preLoaderRoute: typeof EventsEventIdHeatsRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/exports': {
      id: '/events/$eventId/exports'
      path: '/exports'
      fullPath: '/events/$eventId/exports'
      preLoaderRoute: typeof EventsEventIdExportsRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/day-of': {
      id: '/events/$eventId/day-of'
      path: '/day-of'
      fullPath: '/events/$eventId/day-of'
      preLoaderRoute: typeof EventsEventIdDayOfRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/convert': {
      id: '/events/$eventId/convert'
      path: '/convert'
      fullPath: '/events/$eventId/convert'
      preLoaderRoute: typeof EventsEventIdConvertRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/billing': {
      id: '/events/$eventId/billing'
      path: '/billing'
      fullPath: '/events/$eventId/billing'
      preLoaderRoute: typeof EventsEventIdBillingRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/e/$slug/volunteer': {
      id: '/e/$slug/volunteer'
      path: '/e/$slug/volunteer'
      fullPath: '/e/$slug/volunteer'
      preLoaderRoute: typeof ESlugVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/e2e/session': {
      id: '/api/e2e/session'
      path: '/api/e2e/session'
      fullPath: '/api/e2e/session'
      preLoaderRoute: typeof ApiE2eSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crew/import': {
      id: '/api/crew/import'
      path: '/api/crew/import'
      fullPath: '/api/crew/import'
      preLoaderRoute: typeof ApiCrewImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crew/events': {
      id: '/admin/crew/events'
      path: '/events'
      fullPath: '/admin/crew/events'
      preLoaderRoute: typeof AdminCrewEventsRouteImport
      parentRoute: typeof AdminCrewRoute
    }
    '/events/$eventId/discovery/judges': {
      id: '/events/$eventId/discovery/judges'
      path: '/discovery/judges'
      fullPath: '/events/$eventId/discovery/judges'
      preLoaderRoute: typeof EventsEventIdDiscoveryJudgesRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/e/$slug/schedule/$token': {
      id: '/e/$slug/schedule/$token'
      path: '/e/$slug/schedule/$token'
      fullPath: '/e/$slug/schedule/$token'
      preLoaderRoute: typeof ESlugScheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug/consent/$token': {
      id: '/e/$slug/consent/$token'
      path: '/e/$slug/consent/$token'
      fullPath: '/e/$slug/consent/$token'
      preLoaderRoute: typeof ESlugConsentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug/confirm/$token': {
      id: '/e/$slug/confirm/$token'
      path: '/e/$slug/confirm/$token'
      fullPath: '/e/$slug/confirm/$token'
      preLoaderRoute: typeof ESlugConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crew/events/$eventId': {
      id: '/admin/crew/events/$eventId'
      path: '/$eventId'
      fullPath: '/admin/crew/events/$eventId'
      preLoaderRoute: typeof AdminCrewEventsEventIdRouteImport
      parentRoute: typeof AdminCrewEventsRoute
    }
    '/admin/crew/events/$eventId/readiness': {
      id: '/admin/crew/events/$eventId/readiness'
      path: '/readiness'
      fullPath: '/admin/crew/events/$eventId/readiness'
      preLoaderRoute: typeof AdminCrewEventsEventIdReadinessRouteImport
      parentRoute: typeof AdminCrewEventsEventIdRoute
    }
    '/admin/crew/events/$eventId/convert': {
      id: '/admin/crew/events/$eventId/convert'
      path: '/convert'
      fullPath: '/admin/crew/events/$eventId/convert'
      preLoaderRoute: typeof AdminCrewEventsEventIdConvertRouteImport
      parentRoute: typeof AdminCrewEventsEventIdRoute
    }
    '/admin/crew/events/$eventId/billing': {
      id: '/admin/crew/events/$eventId/billing'
      path: '/billing'
      fullPath: '/admin/crew/events/$eventId/billing'
      preLoaderRoute: typeof AdminCrewEventsEventIdBillingRouteImport
      parentRoute: typeof AdminCrewEventsEventIdRoute
    }
  }
}

interface EventsEventIdRouteChildren {
  EventsEventIdBillingRoute: typeof EventsEventIdBillingRoute
  EventsEventIdConvertRoute: typeof EventsEventIdConvertRoute
  EventsEventIdDayOfRoute: typeof EventsEventIdDayOfRoute
  EventsEventIdExportsRoute: typeof EventsEventIdExportsRoute
  EventsEventIdHeatsRoute: typeof EventsEventIdHeatsRoute
  EventsEventIdJudgesRoute: typeof EventsEventIdJudgesRoute
  EventsEventIdMessagesRoute: typeof EventsEventIdMessagesRoute
  EventsEventIdReadinessRoute: typeof EventsEventIdReadinessRoute
  EventsEventIdScheduleRoute: typeof EventsEventIdScheduleRoute
  EventsEventIdSetupRoute: typeof EventsEventIdSetupRoute
  EventsEventIdShiftsRoute: typeof EventsEventIdShiftsRoute
  EventsEventIdStaffingRoute: typeof EventsEventIdStaffingRoute
  EventsEventIdVolunteersRoute: typeof EventsEventIdVolunteersRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  EventsEventIdDiscoveryJudgesRoute: typeof EventsEventIdDiscoveryJudgesRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdBillingRoute: EventsEventIdBillingRoute,
  EventsEventIdConvertRoute: EventsEventIdConvertRoute,
  EventsEventIdDayOfRoute: EventsEventIdDayOfRoute,
  EventsEventIdExportsRoute: EventsEventIdExportsRoute,
  EventsEventIdHeatsRoute: EventsEventIdHeatsRoute,
  EventsEventIdJudgesRoute: EventsEventIdJudgesRoute,
  EventsEventIdMessagesRoute: EventsEventIdMessagesRoute,
  EventsEventIdReadinessRoute: EventsEventIdReadinessRoute,
  EventsEventIdScheduleRoute: EventsEventIdScheduleRoute,
  EventsEventIdSetupRoute: EventsEventIdSetupRoute,
  EventsEventIdShiftsRoute: EventsEventIdShiftsRoute,
  EventsEventIdStaffingRoute: EventsEventIdStaffingRoute,
  EventsEventIdVolunteersRoute: EventsEventIdVolunteersRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  EventsEventIdDiscoveryJudgesRoute: EventsEventIdDiscoveryJudgesRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
  EventsNewRoute: typeof EventsNewRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
  EventsNewRoute: EventsNewRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface AdminCrewEventsEventIdRouteChildren {
  AdminCrewEventsEventIdBillingRoute: typeof AdminCrewEventsEventIdBillingRoute
  AdminCrewEventsEventIdConvertRoute: typeof AdminCrewEventsEventIdConvertRoute
  AdminCrewEventsEventIdReadinessRoute: typeof AdminCrewEventsEventIdReadinessRoute
}

const AdminCrewEventsEventIdRouteChildren: AdminCrewEventsEventIdRouteChildren =
  {
    AdminCrewEventsEventIdBillingRoute: AdminCrewEventsEventIdBillingRoute,
    AdminCrewEventsEventIdConvertRoute: AdminCrewEventsEventIdConvertRoute,
    AdminCrewEventsEventIdReadinessRoute: AdminCrewEventsEventIdReadinessRoute,
  }

const AdminCrewEventsEventIdRouteWithChildren =
  AdminCrewEventsEventIdRoute._addFileChildren(
    AdminCrewEventsEventIdRouteChildren,
  )

interface AdminCrewEventsRouteChildren {
  AdminCrewEventsEventIdRoute: typeof AdminCrewEventsEventIdRouteWithChildren
}

const AdminCrewEventsRouteChildren: AdminCrewEventsRouteChildren = {
  AdminCrewEventsEventIdRoute: AdminCrewEventsEventIdRouteWithChildren,
}

const AdminCrewEventsRouteWithChildren = AdminCrewEventsRoute._addFileChildren(
  AdminCrewEventsRouteChildren,
)

interface AdminCrewRouteChildren {
  AdminCrewEventsRoute: typeof AdminCrewEventsRouteWithChildren
}

const AdminCrewRouteChildren: AdminCrewRouteChildren = {
  AdminCrewEventsRoute: AdminCrewEventsRouteWithChildren,
}

const AdminCrewRouteWithChildren = AdminCrewRoute._addFileChildren(
  AdminCrewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  EventsRoute: EventsRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AdminCrewRoute: AdminCrewRouteWithChildren,
  ApiCrewImportRoute: ApiCrewImportRoute,
  ApiE2eSessionRoute: ApiE2eSessionRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ESlugVolunteerRoute: ESlugVolunteerRoute,
  SeriesGroupIdCrewRoute: SeriesGroupIdCrewRoute,
  ESlugConfirmTokenRoute: ESlugConfirmTokenRoute,
  ESlugConsentTokenRoute: ESlugConsentTokenRoute,
  ESlugScheduleTokenRoute: ESlugScheduleTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
