/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompeteRouteImport } from './routes/compete'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompeteIndexRouteImport } from './routes/compete/index'
import { Route as CompeteOrganizerRouteImport } from './routes/compete/organizer'
import { Route as CompeteSlugRouteImport } from './routes/compete/$slug'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as CompeteOrganizerIndexRouteImport } from './routes/compete/organizer/index'
import { Route as CompeteSlugIndexRouteImport } from './routes/compete/$slug/index'
import { Route as ProtectedWorkoutsIndexRouteImport } from './routes/_protected/workouts/index'
import { Route as ProtectedTeamIndexRouteImport } from './routes/_protected/team/index'
import { Route as ProtectedLogIndexRouteImport } from './routes/_protected/log/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as CompeteOrganizerNewRouteImport } from './routes/compete/organizer/new'
import { Route as CompeteOrganizerCompetitionIdRouteImport } from './routes/compete/organizer/$competitionId'
import { Route as CompeteInviteTokenRouteImport } from './routes/compete/invite/$token'
import { Route as CompeteSlugWorkoutsRouteImport } from './routes/compete/$slug/workouts'
import { Route as CompeteSlugVolunteerRouteImport } from './routes/compete/$slug/volunteer'
import { Route as CompeteSlugScheduleRouteImport } from './routes/compete/$slug/schedule'
import { Route as CompeteSlugRegisterRouteImport } from './routes/compete/$slug/register'
import { Route as CompeteSlugMyScheduleRouteImport } from './routes/compete/$slug/my-schedule'
import { Route as CompeteSlugLeaderboardRouteImport } from './routes/compete/$slug/leaderboard'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as CompeteOrganizerSeriesIndexRouteImport } from './routes/compete/organizer/series/index'
import { Route as CompeteOrganizerCompetitionIdIndexRouteImport } from './routes/compete/organizer/$competitionId/index'
import { Route as ProtectedWorkoutsNewIndexRouteImport } from './routes/_protected/workouts/new/index'
import { Route as ProtectedWorkoutsWorkoutIdIndexRouteImport } from './routes/_protected/workouts/$workoutId/index'
import { Route as ProtectedSettingsProgrammingIndexRouteImport } from './routes/_protected/settings/programming/index'
import { Route as ProtectedLogNewIndexRouteImport } from './routes/_protected/log/new/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as CompeteOrganizerSeriesNewRouteImport } from './routes/compete/organizer/series/new'
import { Route as CompeteOrganizerSeriesGroupIdRouteImport } from './routes/compete/organizer/series/$groupId'
import { Route as CompeteOrganizerCompetitionIdVolunteersRouteImport } from './routes/compete/organizer/$competitionId/volunteers'
import { Route as CompeteOrganizerCompetitionIdSponsorsRouteImport } from './routes/compete/organizer/$competitionId/sponsors'
import { Route as CompeteOrganizerCompetitionIdScheduleRouteImport } from './routes/compete/organizer/$competitionId/schedule'
import { Route as CompeteOrganizerCompetitionIdRevenueRouteImport } from './routes/compete/organizer/$competitionId/revenue'
import { Route as CompeteOrganizerCompetitionIdResultsRouteImport } from './routes/compete/organizer/$competitionId/results'
import { Route as CompeteOrganizerCompetitionIdPricingRouteImport } from './routes/compete/organizer/$competitionId/pricing'
import { Route as CompeteOrganizerCompetitionIdDivisionsRouteImport } from './routes/compete/organizer/$competitionId/divisions'
import { Route as CompeteOrganizerCompetitionIdAthletesRouteImport } from './routes/compete/organizer/$competitionId/athletes'
import { Route as CompeteSlugRegisterSuccessRouteImport } from './routes/compete/$slug/register/success'
import { Route as CompeteOrganizerSeriesGroupIdIndexRouteImport } from './routes/compete/organizer/series/$groupId/index'
import { Route as CompeteOrganizerCompetitionIdEventsIndexRouteImport } from './routes/compete/organizer/$competitionId/events/index'
import { Route as ProtectedWorkoutsWorkoutIdScheduleIndexRouteImport } from './routes/_protected/workouts/$workoutId/schedule/index'
import { Route as ProtectedWorkoutsWorkoutIdEditIndexRouteImport } from './routes/_protected/workouts/$workoutId/edit/index'
import { Route as ProtectedSettingsProgrammingTrackIdIndexRouteImport } from './routes/_protected/settings/programming/$trackId/index'
import { Route as CompeteOrganizerSeriesGroupIdEditRouteImport } from './routes/compete/organizer/series/$groupId/edit'
import { Route as CompeteOrganizerCompetitionIdEventsEventIdRouteImport } from './routes/compete/organizer/$competitionId/events/$eventId'

const CompeteRoute = CompeteRouteImport.update({
  id: '/compete',
  path: '/compete',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompeteIndexRoute = CompeteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompeteRoute,
} as any)
const CompeteOrganizerRoute = CompeteOrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => CompeteRoute,
} as any)
const CompeteSlugRoute = CompeteSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompeteRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const CompeteOrganizerIndexRoute = CompeteOrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompeteOrganizerRoute,
} as any)
const CompeteSlugIndexRoute = CompeteSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompeteSlugRoute,
} as any)
const ProtectedWorkoutsIndexRoute = ProtectedWorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTeamIndexRoute = ProtectedTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLogIndexRoute = ProtectedLogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => ProtectedRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const CompeteOrganizerNewRoute = CompeteOrganizerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CompeteOrganizerRoute,
} as any)
const CompeteOrganizerCompetitionIdRoute =
  CompeteOrganizerCompetitionIdRouteImport.update({
    id: '/$competitionId',
    path: '/$competitionId',
    getParentRoute: () => CompeteOrganizerRoute,
  } as any)
const CompeteInviteTokenRoute = CompeteInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => CompeteRoute,
} as any)
const CompeteSlugWorkoutsRoute = CompeteSlugWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => CompeteSlugRoute,
} as any)
const CompeteSlugVolunteerRoute = CompeteSlugVolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => CompeteSlugRoute,
} as any)
const CompeteSlugScheduleRoute = CompeteSlugScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => CompeteSlugRoute,
} as any)
const CompeteSlugRegisterRoute = CompeteSlugRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => CompeteSlugRoute,
} as any)
const CompeteSlugMyScheduleRoute = CompeteSlugMyScheduleRouteImport.update({
  id: '/my-schedule',
  path: '/my-schedule',
  getParentRoute: () => CompeteSlugRoute,
} as any)
const CompeteSlugLeaderboardRoute = CompeteSlugLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => CompeteSlugRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompeteOrganizerSeriesIndexRoute =
  CompeteOrganizerSeriesIndexRouteImport.update({
    id: '/series/',
    path: '/series/',
    getParentRoute: () => CompeteOrganizerRoute,
  } as any)
const CompeteOrganizerCompetitionIdIndexRoute =
  CompeteOrganizerCompetitionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompeteOrganizerCompetitionIdRoute,
  } as any)
const ProtectedWorkoutsNewIndexRoute =
  ProtectedWorkoutsNewIndexRouteImport.update({
    id: '/workouts/new/',
    path: '/workouts/new/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedWorkoutsWorkoutIdIndexRoute =
  ProtectedWorkoutsWorkoutIdIndexRouteImport.update({
    id: '/workouts/$workoutId/',
    path: '/workouts/$workoutId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsProgrammingIndexRoute =
  ProtectedSettingsProgrammingIndexRouteImport.update({
    id: '/programming/',
    path: '/programming/',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedLogNewIndexRoute = ProtectedLogNewIndexRouteImport.update({
  id: '/log/new/',
  path: '/log/new/',
  getParentRoute: () => ProtectedRoute,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const CompeteOrganizerSeriesNewRoute =
  CompeteOrganizerSeriesNewRouteImport.update({
    id: '/series/new',
    path: '/series/new',
    getParentRoute: () => CompeteOrganizerRoute,
  } as any)
const CompeteOrganizerSeriesGroupIdRoute =
  CompeteOrganizerSeriesGroupIdRouteImport.update({
    id: '/series/$groupId',
    path: '/series/$groupId',
    getParentRoute: () => CompeteOrganizerRoute,
  } as any)
const CompeteOrganizerCompetitionIdVolunteersRoute =
  CompeteOrganizerCompetitionIdVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => CompeteOrganizerCompetitionIdRoute,
  } as any)
const CompeteOrganizerCompetitionIdSponsorsRoute =
  CompeteOrganizerCompetitionIdSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => CompeteOrganizerCompetitionIdRoute,
  } as any)
const CompeteOrganizerCompetitionIdScheduleRoute =
  CompeteOrganizerCompetitionIdScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => CompeteOrganizerCompetitionIdRoute,
  } as any)
const CompeteOrganizerCompetitionIdRevenueRoute =
  CompeteOrganizerCompetitionIdRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => CompeteOrganizerCompetitionIdRoute,
  } as any)
const CompeteOrganizerCompetitionIdResultsRoute =
  CompeteOrganizerCompetitionIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => CompeteOrganizerCompetitionIdRoute,
  } as any)
const CompeteOrganizerCompetitionIdPricingRoute =
  CompeteOrganizerCompetitionIdPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => CompeteOrganizerCompetitionIdRoute,
  } as any)
const CompeteOrganizerCompetitionIdDivisionsRoute =
  CompeteOrganizerCompetitionIdDivisionsRouteImport.update({
    id: '/divisions',
    path: '/divisions',
    getParentRoute: () => CompeteOrganizerCompetitionIdRoute,
  } as any)
const CompeteOrganizerCompetitionIdAthletesRoute =
  CompeteOrganizerCompetitionIdAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => CompeteOrganizerCompetitionIdRoute,
  } as any)
const CompeteSlugRegisterSuccessRoute =
  CompeteSlugRegisterSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => CompeteSlugRegisterRoute,
  } as any)
const CompeteOrganizerSeriesGroupIdIndexRoute =
  CompeteOrganizerSeriesGroupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompeteOrganizerSeriesGroupIdRoute,
  } as any)
const CompeteOrganizerCompetitionIdEventsIndexRoute =
  CompeteOrganizerCompetitionIdEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => CompeteOrganizerCompetitionIdRoute,
  } as any)
const ProtectedWorkoutsWorkoutIdScheduleIndexRoute =
  ProtectedWorkoutsWorkoutIdScheduleIndexRouteImport.update({
    id: '/workouts/$workoutId/schedule/',
    path: '/workouts/$workoutId/schedule/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedWorkoutsWorkoutIdEditIndexRoute =
  ProtectedWorkoutsWorkoutIdEditIndexRouteImport.update({
    id: '/workouts/$workoutId/edit/',
    path: '/workouts/$workoutId/edit/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsProgrammingTrackIdIndexRoute =
  ProtectedSettingsProgrammingTrackIdIndexRouteImport.update({
    id: '/programming/$trackId/',
    path: '/programming/$trackId/',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const CompeteOrganizerSeriesGroupIdEditRoute =
  CompeteOrganizerSeriesGroupIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => CompeteOrganizerSeriesGroupIdRoute,
  } as any)
const CompeteOrganizerCompetitionIdEventsEventIdRoute =
  CompeteOrganizerCompetitionIdEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => CompeteOrganizerCompetitionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compete': typeof CompeteRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/compete/$slug': typeof CompeteSlugRouteWithChildren
  '/compete/organizer': typeof CompeteOrganizerRouteWithChildren
  '/compete/': typeof CompeteIndexRoute
  '/compete/$slug/leaderboard': typeof CompeteSlugLeaderboardRoute
  '/compete/$slug/my-schedule': typeof CompeteSlugMyScheduleRoute
  '/compete/$slug/register': typeof CompeteSlugRegisterRouteWithChildren
  '/compete/$slug/schedule': typeof CompeteSlugScheduleRoute
  '/compete/$slug/volunteer': typeof CompeteSlugVolunteerRoute
  '/compete/$slug/workouts': typeof CompeteSlugWorkoutsRoute
  '/compete/invite/$token': typeof CompeteInviteTokenRoute
  '/compete/organizer/$competitionId': typeof CompeteOrganizerCompetitionIdRouteWithChildren
  '/compete/organizer/new': typeof CompeteOrganizerNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/log': typeof ProtectedLogIndexRoute
  '/team': typeof ProtectedTeamIndexRoute
  '/workouts': typeof ProtectedWorkoutsIndexRoute
  '/compete/$slug/': typeof CompeteSlugIndexRoute
  '/compete/organizer/': typeof CompeteOrganizerIndexRoute
  '/compete/$slug/register/success': typeof CompeteSlugRegisterSuccessRoute
  '/compete/organizer/$competitionId/athletes': typeof CompeteOrganizerCompetitionIdAthletesRoute
  '/compete/organizer/$competitionId/divisions': typeof CompeteOrganizerCompetitionIdDivisionsRoute
  '/compete/organizer/$competitionId/pricing': typeof CompeteOrganizerCompetitionIdPricingRoute
  '/compete/organizer/$competitionId/results': typeof CompeteOrganizerCompetitionIdResultsRoute
  '/compete/organizer/$competitionId/revenue': typeof CompeteOrganizerCompetitionIdRevenueRoute
  '/compete/organizer/$competitionId/schedule': typeof CompeteOrganizerCompetitionIdScheduleRoute
  '/compete/organizer/$competitionId/sponsors': typeof CompeteOrganizerCompetitionIdSponsorsRoute
  '/compete/organizer/$competitionId/volunteers': typeof CompeteOrganizerCompetitionIdVolunteersRoute
  '/compete/organizer/series/$groupId': typeof CompeteOrganizerSeriesGroupIdRouteWithChildren
  '/compete/organizer/series/new': typeof CompeteOrganizerSeriesNewRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/log/new': typeof ProtectedLogNewIndexRoute
  '/settings/programming': typeof ProtectedSettingsProgrammingIndexRoute
  '/workouts/$workoutId': typeof ProtectedWorkoutsWorkoutIdIndexRoute
  '/workouts/new': typeof ProtectedWorkoutsNewIndexRoute
  '/compete/organizer/$competitionId/': typeof CompeteOrganizerCompetitionIdIndexRoute
  '/compete/organizer/series': typeof CompeteOrganizerSeriesIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/compete/organizer/$competitionId/events/$eventId': typeof CompeteOrganizerCompetitionIdEventsEventIdRoute
  '/compete/organizer/series/$groupId/edit': typeof CompeteOrganizerSeriesGroupIdEditRoute
  '/settings/programming/$trackId': typeof ProtectedSettingsProgrammingTrackIdIndexRoute
  '/workouts/$workoutId/edit': typeof ProtectedWorkoutsWorkoutIdEditIndexRoute
  '/workouts/$workoutId/schedule': typeof ProtectedWorkoutsWorkoutIdScheduleIndexRoute
  '/compete/organizer/$competitionId/events': typeof CompeteOrganizerCompetitionIdEventsIndexRoute
  '/compete/organizer/series/$groupId/': typeof CompeteOrganizerSeriesGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/compete': typeof CompeteIndexRoute
  '/compete/$slug/leaderboard': typeof CompeteSlugLeaderboardRoute
  '/compete/$slug/my-schedule': typeof CompeteSlugMyScheduleRoute
  '/compete/$slug/register': typeof CompeteSlugRegisterRouteWithChildren
  '/compete/$slug/schedule': typeof CompeteSlugScheduleRoute
  '/compete/$slug/volunteer': typeof CompeteSlugVolunteerRoute
  '/compete/$slug/workouts': typeof CompeteSlugWorkoutsRoute
  '/compete/invite/$token': typeof CompeteInviteTokenRoute
  '/compete/organizer/new': typeof CompeteOrganizerNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/log': typeof ProtectedLogIndexRoute
  '/team': typeof ProtectedTeamIndexRoute
  '/workouts': typeof ProtectedWorkoutsIndexRoute
  '/compete/$slug': typeof CompeteSlugIndexRoute
  '/compete/organizer': typeof CompeteOrganizerIndexRoute
  '/compete/$slug/register/success': typeof CompeteSlugRegisterSuccessRoute
  '/compete/organizer/$competitionId/athletes': typeof CompeteOrganizerCompetitionIdAthletesRoute
  '/compete/organizer/$competitionId/divisions': typeof CompeteOrganizerCompetitionIdDivisionsRoute
  '/compete/organizer/$competitionId/pricing': typeof CompeteOrganizerCompetitionIdPricingRoute
  '/compete/organizer/$competitionId/results': typeof CompeteOrganizerCompetitionIdResultsRoute
  '/compete/organizer/$competitionId/revenue': typeof CompeteOrganizerCompetitionIdRevenueRoute
  '/compete/organizer/$competitionId/schedule': typeof CompeteOrganizerCompetitionIdScheduleRoute
  '/compete/organizer/$competitionId/sponsors': typeof CompeteOrganizerCompetitionIdSponsorsRoute
  '/compete/organizer/$competitionId/volunteers': typeof CompeteOrganizerCompetitionIdVolunteersRoute
  '/compete/organizer/series/new': typeof CompeteOrganizerSeriesNewRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/log/new': typeof ProtectedLogNewIndexRoute
  '/settings/programming': typeof ProtectedSettingsProgrammingIndexRoute
  '/workouts/$workoutId': typeof ProtectedWorkoutsWorkoutIdIndexRoute
  '/workouts/new': typeof ProtectedWorkoutsNewIndexRoute
  '/compete/organizer/$competitionId': typeof CompeteOrganizerCompetitionIdIndexRoute
  '/compete/organizer/series': typeof CompeteOrganizerSeriesIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
  '/compete/organizer/$competitionId/events/$eventId': typeof CompeteOrganizerCompetitionIdEventsEventIdRoute
  '/compete/organizer/series/$groupId/edit': typeof CompeteOrganizerSeriesGroupIdEditRoute
  '/settings/programming/$trackId': typeof ProtectedSettingsProgrammingTrackIdIndexRoute
  '/workouts/$workoutId/edit': typeof ProtectedWorkoutsWorkoutIdEditIndexRoute
  '/workouts/$workoutId/schedule': typeof ProtectedWorkoutsWorkoutIdScheduleIndexRoute
  '/compete/organizer/$competitionId/events': typeof CompeteOrganizerCompetitionIdEventsIndexRoute
  '/compete/organizer/series/$groupId': typeof CompeteOrganizerSeriesGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/compete': typeof CompeteRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/settings': typeof ProtectedSettingsRouteWithChildren
  '/compete/$slug': typeof CompeteSlugRouteWithChildren
  '/compete/organizer': typeof CompeteOrganizerRouteWithChildren
  '/compete/': typeof CompeteIndexRoute
  '/compete/$slug/leaderboard': typeof CompeteSlugLeaderboardRoute
  '/compete/$slug/my-schedule': typeof CompeteSlugMyScheduleRoute
  '/compete/$slug/register': typeof CompeteSlugRegisterRouteWithChildren
  '/compete/$slug/schedule': typeof CompeteSlugScheduleRoute
  '/compete/$slug/volunteer': typeof CompeteSlugVolunteerRoute
  '/compete/$slug/workouts': typeof CompeteSlugWorkoutsRoute
  '/compete/invite/$token': typeof CompeteInviteTokenRoute
  '/compete/organizer/$competitionId': typeof CompeteOrganizerCompetitionIdRouteWithChildren
  '/compete/organizer/new': typeof CompeteOrganizerNewRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_protected/log/': typeof ProtectedLogIndexRoute
  '/_protected/team/': typeof ProtectedTeamIndexRoute
  '/_protected/workouts/': typeof ProtectedWorkoutsIndexRoute
  '/compete/$slug/': typeof CompeteSlugIndexRoute
  '/compete/organizer/': typeof CompeteOrganizerIndexRoute
  '/compete/$slug/register/success': typeof CompeteSlugRegisterSuccessRoute
  '/compete/organizer/$competitionId/athletes': typeof CompeteOrganizerCompetitionIdAthletesRoute
  '/compete/organizer/$competitionId/divisions': typeof CompeteOrganizerCompetitionIdDivisionsRoute
  '/compete/organizer/$competitionId/pricing': typeof CompeteOrganizerCompetitionIdPricingRoute
  '/compete/organizer/$competitionId/results': typeof CompeteOrganizerCompetitionIdResultsRoute
  '/compete/organizer/$competitionId/revenue': typeof CompeteOrganizerCompetitionIdRevenueRoute
  '/compete/organizer/$competitionId/schedule': typeof CompeteOrganizerCompetitionIdScheduleRoute
  '/compete/organizer/$competitionId/sponsors': typeof CompeteOrganizerCompetitionIdSponsorsRoute
  '/compete/organizer/$competitionId/volunteers': typeof CompeteOrganizerCompetitionIdVolunteersRoute
  '/compete/organizer/series/$groupId': typeof CompeteOrganizerSeriesGroupIdRouteWithChildren
  '/compete/organizer/series/new': typeof CompeteOrganizerSeriesNewRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/_protected/log/new/': typeof ProtectedLogNewIndexRoute
  '/_protected/settings/programming/': typeof ProtectedSettingsProgrammingIndexRoute
  '/_protected/workouts/$workoutId/': typeof ProtectedWorkoutsWorkoutIdIndexRoute
  '/_protected/workouts/new/': typeof ProtectedWorkoutsNewIndexRoute
  '/compete/organizer/$competitionId/': typeof CompeteOrganizerCompetitionIdIndexRoute
  '/compete/organizer/series/': typeof CompeteOrganizerSeriesIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
  '/compete/organizer/$competitionId/events/$eventId': typeof CompeteOrganizerCompetitionIdEventsEventIdRoute
  '/compete/organizer/series/$groupId/edit': typeof CompeteOrganizerSeriesGroupIdEditRoute
  '/_protected/settings/programming/$trackId/': typeof ProtectedSettingsProgrammingTrackIdIndexRoute
  '/_protected/workouts/$workoutId/edit/': typeof ProtectedWorkoutsWorkoutIdEditIndexRoute
  '/_protected/workouts/$workoutId/schedule/': typeof ProtectedWorkoutsWorkoutIdScheduleIndexRoute
  '/compete/organizer/$competitionId/events/': typeof CompeteOrganizerCompetitionIdEventsIndexRoute
  '/compete/organizer/series/$groupId/': typeof CompeteOrganizerSeriesGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compete'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/settings'
    | '/compete/$slug'
    | '/compete/organizer'
    | '/compete/'
    | '/compete/$slug/leaderboard'
    | '/compete/$slug/my-schedule'
    | '/compete/$slug/register'
    | '/compete/$slug/schedule'
    | '/compete/$slug/volunteer'
    | '/compete/$slug/workouts'
    | '/compete/invite/$token'
    | '/compete/organizer/$competitionId'
    | '/compete/organizer/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/log'
    | '/team'
    | '/workouts'
    | '/compete/$slug/'
    | '/compete/organizer/'
    | '/compete/$slug/register/success'
    | '/compete/organizer/$competitionId/athletes'
    | '/compete/organizer/$competitionId/divisions'
    | '/compete/organizer/$competitionId/pricing'
    | '/compete/organizer/$competitionId/results'
    | '/compete/organizer/$competitionId/revenue'
    | '/compete/organizer/$competitionId/schedule'
    | '/compete/organizer/$competitionId/sponsors'
    | '/compete/organizer/$competitionId/volunteers'
    | '/compete/organizer/series/$groupId'
    | '/compete/organizer/series/new'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/log/new'
    | '/settings/programming'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/compete/organizer/$competitionId/'
    | '/compete/organizer/series'
    | '/demo/start/ssr'
    | '/compete/organizer/$competitionId/events/$eventId'
    | '/compete/organizer/series/$groupId/edit'
    | '/settings/programming/$trackId'
    | '/workouts/$workoutId/edit'
    | '/workouts/$workoutId/schedule'
    | '/compete/organizer/$competitionId/events'
    | '/compete/organizer/series/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/settings'
    | '/compete'
    | '/compete/$slug/leaderboard'
    | '/compete/$slug/my-schedule'
    | '/compete/$slug/register'
    | '/compete/$slug/schedule'
    | '/compete/$slug/volunteer'
    | '/compete/$slug/workouts'
    | '/compete/invite/$token'
    | '/compete/organizer/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/log'
    | '/team'
    | '/workouts'
    | '/compete/$slug'
    | '/compete/organizer'
    | '/compete/$slug/register/success'
    | '/compete/organizer/$competitionId/athletes'
    | '/compete/organizer/$competitionId/divisions'
    | '/compete/organizer/$competitionId/pricing'
    | '/compete/organizer/$competitionId/results'
    | '/compete/organizer/$competitionId/revenue'
    | '/compete/organizer/$competitionId/schedule'
    | '/compete/organizer/$competitionId/sponsors'
    | '/compete/organizer/$competitionId/volunteers'
    | '/compete/organizer/series/new'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/log/new'
    | '/settings/programming'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/compete/organizer/$competitionId'
    | '/compete/organizer/series'
    | '/demo/start/ssr'
    | '/compete/organizer/$competitionId/events/$eventId'
    | '/compete/organizer/series/$groupId/edit'
    | '/settings/programming/$trackId'
    | '/workouts/$workoutId/edit'
    | '/workouts/$workoutId/schedule'
    | '/compete/organizer/$competitionId/events'
    | '/compete/organizer/series/$groupId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/compete'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/dashboard'
    | '/_protected/settings'
    | '/compete/$slug'
    | '/compete/organizer'
    | '/compete/'
    | '/compete/$slug/leaderboard'
    | '/compete/$slug/my-schedule'
    | '/compete/$slug/register'
    | '/compete/$slug/schedule'
    | '/compete/$slug/volunteer'
    | '/compete/$slug/workouts'
    | '/compete/invite/$token'
    | '/compete/organizer/$competitionId'
    | '/compete/organizer/new'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/_protected/log/'
    | '/_protected/team/'
    | '/_protected/workouts/'
    | '/compete/$slug/'
    | '/compete/organizer/'
    | '/compete/$slug/register/success'
    | '/compete/organizer/$competitionId/athletes'
    | '/compete/organizer/$competitionId/divisions'
    | '/compete/organizer/$competitionId/pricing'
    | '/compete/organizer/$competitionId/results'
    | '/compete/organizer/$competitionId/revenue'
    | '/compete/organizer/$competitionId/schedule'
    | '/compete/organizer/$competitionId/sponsors'
    | '/compete/organizer/$competitionId/volunteers'
    | '/compete/organizer/series/$groupId'
    | '/compete/organizer/series/new'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/_protected/log/new/'
    | '/_protected/settings/programming/'
    | '/_protected/workouts/$workoutId/'
    | '/_protected/workouts/new/'
    | '/compete/organizer/$competitionId/'
    | '/compete/organizer/series/'
    | '/demo/start/ssr/'
    | '/compete/organizer/$competitionId/events/$eventId'
    | '/compete/organizer/series/$groupId/edit'
    | '/_protected/settings/programming/$trackId/'
    | '/_protected/workouts/$workoutId/edit/'
    | '/_protected/workouts/$workoutId/schedule/'
    | '/compete/organizer/$competitionId/events/'
    | '/compete/organizer/series/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  CompeteRoute: typeof CompeteRouteWithChildren
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compete': {
      id: '/compete'
      path: '/compete'
      fullPath: '/compete'
      preLoaderRoute: typeof CompeteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compete/': {
      id: '/compete/'
      path: '/'
      fullPath: '/compete/'
      preLoaderRoute: typeof CompeteIndexRouteImport
      parentRoute: typeof CompeteRoute
    }
    '/compete/organizer': {
      id: '/compete/organizer'
      path: '/organizer'
      fullPath: '/compete/organizer'
      preLoaderRoute: typeof CompeteOrganizerRouteImport
      parentRoute: typeof CompeteRoute
    }
    '/compete/$slug': {
      id: '/compete/$slug'
      path: '/$slug'
      fullPath: '/compete/$slug'
      preLoaderRoute: typeof CompeteSlugRouteImport
      parentRoute: typeof CompeteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/compete/organizer/': {
      id: '/compete/organizer/'
      path: '/'
      fullPath: '/compete/organizer/'
      preLoaderRoute: typeof CompeteOrganizerIndexRouteImport
      parentRoute: typeof CompeteOrganizerRoute
    }
    '/compete/$slug/': {
      id: '/compete/$slug/'
      path: '/'
      fullPath: '/compete/$slug/'
      preLoaderRoute: typeof CompeteSlugIndexRouteImport
      parentRoute: typeof CompeteSlugRoute
    }
    '/_protected/workouts/': {
      id: '/_protected/workouts/'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof ProtectedWorkoutsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/team/': {
      id: '/_protected/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ProtectedTeamIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/log/': {
      id: '/_protected/log/'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof ProtectedLogIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compete/organizer/new': {
      id: '/compete/organizer/new'
      path: '/new'
      fullPath: '/compete/organizer/new'
      preLoaderRoute: typeof CompeteOrganizerNewRouteImport
      parentRoute: typeof CompeteOrganizerRoute
    }
    '/compete/organizer/$competitionId': {
      id: '/compete/organizer/$competitionId'
      path: '/$competitionId'
      fullPath: '/compete/organizer/$competitionId'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdRouteImport
      parentRoute: typeof CompeteOrganizerRoute
    }
    '/compete/invite/$token': {
      id: '/compete/invite/$token'
      path: '/invite/$token'
      fullPath: '/compete/invite/$token'
      preLoaderRoute: typeof CompeteInviteTokenRouteImport
      parentRoute: typeof CompeteRoute
    }
    '/compete/$slug/workouts': {
      id: '/compete/$slug/workouts'
      path: '/workouts'
      fullPath: '/compete/$slug/workouts'
      preLoaderRoute: typeof CompeteSlugWorkoutsRouteImport
      parentRoute: typeof CompeteSlugRoute
    }
    '/compete/$slug/volunteer': {
      id: '/compete/$slug/volunteer'
      path: '/volunteer'
      fullPath: '/compete/$slug/volunteer'
      preLoaderRoute: typeof CompeteSlugVolunteerRouteImport
      parentRoute: typeof CompeteSlugRoute
    }
    '/compete/$slug/schedule': {
      id: '/compete/$slug/schedule'
      path: '/schedule'
      fullPath: '/compete/$slug/schedule'
      preLoaderRoute: typeof CompeteSlugScheduleRouteImport
      parentRoute: typeof CompeteSlugRoute
    }
    '/compete/$slug/register': {
      id: '/compete/$slug/register'
      path: '/register'
      fullPath: '/compete/$slug/register'
      preLoaderRoute: typeof CompeteSlugRegisterRouteImport
      parentRoute: typeof CompeteSlugRoute
    }
    '/compete/$slug/my-schedule': {
      id: '/compete/$slug/my-schedule'
      path: '/my-schedule'
      fullPath: '/compete/$slug/my-schedule'
      preLoaderRoute: typeof CompeteSlugMyScheduleRouteImport
      parentRoute: typeof CompeteSlugRoute
    }
    '/compete/$slug/leaderboard': {
      id: '/compete/$slug/leaderboard'
      path: '/leaderboard'
      fullPath: '/compete/$slug/leaderboard'
      preLoaderRoute: typeof CompeteSlugLeaderboardRouteImport
      parentRoute: typeof CompeteSlugRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compete/organizer/series/': {
      id: '/compete/organizer/series/'
      path: '/series'
      fullPath: '/compete/organizer/series'
      preLoaderRoute: typeof CompeteOrganizerSeriesIndexRouteImport
      parentRoute: typeof CompeteOrganizerRoute
    }
    '/compete/organizer/$competitionId/': {
      id: '/compete/organizer/$competitionId/'
      path: '/'
      fullPath: '/compete/organizer/$competitionId/'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdIndexRouteImport
      parentRoute: typeof CompeteOrganizerCompetitionIdRoute
    }
    '/_protected/workouts/new/': {
      id: '/_protected/workouts/new/'
      path: '/workouts/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof ProtectedWorkoutsNewIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workouts/$workoutId/': {
      id: '/_protected/workouts/$workoutId/'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof ProtectedWorkoutsWorkoutIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/programming/': {
      id: '/_protected/settings/programming/'
      path: '/programming'
      fullPath: '/settings/programming'
      preLoaderRoute: typeof ProtectedSettingsProgrammingIndexRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/log/new/': {
      id: '/_protected/log/new/'
      path: '/log/new'
      fullPath: '/log/new'
      preLoaderRoute: typeof ProtectedLogNewIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compete/organizer/series/new': {
      id: '/compete/organizer/series/new'
      path: '/series/new'
      fullPath: '/compete/organizer/series/new'
      preLoaderRoute: typeof CompeteOrganizerSeriesNewRouteImport
      parentRoute: typeof CompeteOrganizerRoute
    }
    '/compete/organizer/series/$groupId': {
      id: '/compete/organizer/series/$groupId'
      path: '/series/$groupId'
      fullPath: '/compete/organizer/series/$groupId'
      preLoaderRoute: typeof CompeteOrganizerSeriesGroupIdRouteImport
      parentRoute: typeof CompeteOrganizerRoute
    }
    '/compete/organizer/$competitionId/volunteers': {
      id: '/compete/organizer/$competitionId/volunteers'
      path: '/volunteers'
      fullPath: '/compete/organizer/$competitionId/volunteers'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdVolunteersRouteImport
      parentRoute: typeof CompeteOrganizerCompetitionIdRoute
    }
    '/compete/organizer/$competitionId/sponsors': {
      id: '/compete/organizer/$competitionId/sponsors'
      path: '/sponsors'
      fullPath: '/compete/organizer/$competitionId/sponsors'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdSponsorsRouteImport
      parentRoute: typeof CompeteOrganizerCompetitionIdRoute
    }
    '/compete/organizer/$competitionId/schedule': {
      id: '/compete/organizer/$competitionId/schedule'
      path: '/schedule'
      fullPath: '/compete/organizer/$competitionId/schedule'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdScheduleRouteImport
      parentRoute: typeof CompeteOrganizerCompetitionIdRoute
    }
    '/compete/organizer/$competitionId/revenue': {
      id: '/compete/organizer/$competitionId/revenue'
      path: '/revenue'
      fullPath: '/compete/organizer/$competitionId/revenue'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdRevenueRouteImport
      parentRoute: typeof CompeteOrganizerCompetitionIdRoute
    }
    '/compete/organizer/$competitionId/results': {
      id: '/compete/organizer/$competitionId/results'
      path: '/results'
      fullPath: '/compete/organizer/$competitionId/results'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdResultsRouteImport
      parentRoute: typeof CompeteOrganizerCompetitionIdRoute
    }
    '/compete/organizer/$competitionId/pricing': {
      id: '/compete/organizer/$competitionId/pricing'
      path: '/pricing'
      fullPath: '/compete/organizer/$competitionId/pricing'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdPricingRouteImport
      parentRoute: typeof CompeteOrganizerCompetitionIdRoute
    }
    '/compete/organizer/$competitionId/divisions': {
      id: '/compete/organizer/$competitionId/divisions'
      path: '/divisions'
      fullPath: '/compete/organizer/$competitionId/divisions'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdDivisionsRouteImport
      parentRoute: typeof CompeteOrganizerCompetitionIdRoute
    }
    '/compete/organizer/$competitionId/athletes': {
      id: '/compete/organizer/$competitionId/athletes'
      path: '/athletes'
      fullPath: '/compete/organizer/$competitionId/athletes'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdAthletesRouteImport
      parentRoute: typeof CompeteOrganizerCompetitionIdRoute
    }
    '/compete/$slug/register/success': {
      id: '/compete/$slug/register/success'
      path: '/success'
      fullPath: '/compete/$slug/register/success'
      preLoaderRoute: typeof CompeteSlugRegisterSuccessRouteImport
      parentRoute: typeof CompeteSlugRegisterRoute
    }
    '/compete/organizer/series/$groupId/': {
      id: '/compete/organizer/series/$groupId/'
      path: '/'
      fullPath: '/compete/organizer/series/$groupId/'
      preLoaderRoute: typeof CompeteOrganizerSeriesGroupIdIndexRouteImport
      parentRoute: typeof CompeteOrganizerSeriesGroupIdRoute
    }
    '/compete/organizer/$competitionId/events/': {
      id: '/compete/organizer/$competitionId/events/'
      path: '/events'
      fullPath: '/compete/organizer/$competitionId/events'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdEventsIndexRouteImport
      parentRoute: typeof CompeteOrganizerCompetitionIdRoute
    }
    '/_protected/workouts/$workoutId/schedule/': {
      id: '/_protected/workouts/$workoutId/schedule/'
      path: '/workouts/$workoutId/schedule'
      fullPath: '/workouts/$workoutId/schedule'
      preLoaderRoute: typeof ProtectedWorkoutsWorkoutIdScheduleIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workouts/$workoutId/edit/': {
      id: '/_protected/workouts/$workoutId/edit/'
      path: '/workouts/$workoutId/edit'
      fullPath: '/workouts/$workoutId/edit'
      preLoaderRoute: typeof ProtectedWorkoutsWorkoutIdEditIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/programming/$trackId/': {
      id: '/_protected/settings/programming/$trackId/'
      path: '/programming/$trackId'
      fullPath: '/settings/programming/$trackId'
      preLoaderRoute: typeof ProtectedSettingsProgrammingTrackIdIndexRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/compete/organizer/series/$groupId/edit': {
      id: '/compete/organizer/series/$groupId/edit'
      path: '/edit'
      fullPath: '/compete/organizer/series/$groupId/edit'
      preLoaderRoute: typeof CompeteOrganizerSeriesGroupIdEditRouteImport
      parentRoute: typeof CompeteOrganizerSeriesGroupIdRoute
    }
    '/compete/organizer/$competitionId/events/$eventId': {
      id: '/compete/organizer/$competitionId/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/compete/organizer/$competitionId/events/$eventId'
      preLoaderRoute: typeof CompeteOrganizerCompetitionIdEventsEventIdRouteImport
      parentRoute: typeof CompeteOrganizerCompetitionIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedSettingsRouteChildren {
  ProtectedSettingsProgrammingIndexRoute: typeof ProtectedSettingsProgrammingIndexRoute
  ProtectedSettingsProgrammingTrackIdIndexRoute: typeof ProtectedSettingsProgrammingTrackIdIndexRoute
}

const ProtectedSettingsRouteChildren: ProtectedSettingsRouteChildren = {
  ProtectedSettingsProgrammingIndexRoute:
    ProtectedSettingsProgrammingIndexRoute,
  ProtectedSettingsProgrammingTrackIdIndexRoute:
    ProtectedSettingsProgrammingTrackIdIndexRoute,
}

const ProtectedSettingsRouteWithChildren =
  ProtectedSettingsRoute._addFileChildren(ProtectedSettingsRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRouteWithChildren
  ProtectedLogIndexRoute: typeof ProtectedLogIndexRoute
  ProtectedTeamIndexRoute: typeof ProtectedTeamIndexRoute
  ProtectedWorkoutsIndexRoute: typeof ProtectedWorkoutsIndexRoute
  ProtectedLogNewIndexRoute: typeof ProtectedLogNewIndexRoute
  ProtectedWorkoutsWorkoutIdIndexRoute: typeof ProtectedWorkoutsWorkoutIdIndexRoute
  ProtectedWorkoutsNewIndexRoute: typeof ProtectedWorkoutsNewIndexRoute
  ProtectedWorkoutsWorkoutIdEditIndexRoute: typeof ProtectedWorkoutsWorkoutIdEditIndexRoute
  ProtectedWorkoutsWorkoutIdScheduleIndexRoute: typeof ProtectedWorkoutsWorkoutIdScheduleIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedSettingsRoute: ProtectedSettingsRouteWithChildren,
  ProtectedLogIndexRoute: ProtectedLogIndexRoute,
  ProtectedTeamIndexRoute: ProtectedTeamIndexRoute,
  ProtectedWorkoutsIndexRoute: ProtectedWorkoutsIndexRoute,
  ProtectedLogNewIndexRoute: ProtectedLogNewIndexRoute,
  ProtectedWorkoutsWorkoutIdIndexRoute: ProtectedWorkoutsWorkoutIdIndexRoute,
  ProtectedWorkoutsNewIndexRoute: ProtectedWorkoutsNewIndexRoute,
  ProtectedWorkoutsWorkoutIdEditIndexRoute:
    ProtectedWorkoutsWorkoutIdEditIndexRoute,
  ProtectedWorkoutsWorkoutIdScheduleIndexRoute:
    ProtectedWorkoutsWorkoutIdScheduleIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface CompeteSlugRegisterRouteChildren {
  CompeteSlugRegisterSuccessRoute: typeof CompeteSlugRegisterSuccessRoute
}

const CompeteSlugRegisterRouteChildren: CompeteSlugRegisterRouteChildren = {
  CompeteSlugRegisterSuccessRoute: CompeteSlugRegisterSuccessRoute,
}

const CompeteSlugRegisterRouteWithChildren =
  CompeteSlugRegisterRoute._addFileChildren(CompeteSlugRegisterRouteChildren)

interface CompeteSlugRouteChildren {
  CompeteSlugLeaderboardRoute: typeof CompeteSlugLeaderboardRoute
  CompeteSlugMyScheduleRoute: typeof CompeteSlugMyScheduleRoute
  CompeteSlugRegisterRoute: typeof CompeteSlugRegisterRouteWithChildren
  CompeteSlugScheduleRoute: typeof CompeteSlugScheduleRoute
  CompeteSlugVolunteerRoute: typeof CompeteSlugVolunteerRoute
  CompeteSlugWorkoutsRoute: typeof CompeteSlugWorkoutsRoute
  CompeteSlugIndexRoute: typeof CompeteSlugIndexRoute
}

const CompeteSlugRouteChildren: CompeteSlugRouteChildren = {
  CompeteSlugLeaderboardRoute: CompeteSlugLeaderboardRoute,
  CompeteSlugMyScheduleRoute: CompeteSlugMyScheduleRoute,
  CompeteSlugRegisterRoute: CompeteSlugRegisterRouteWithChildren,
  CompeteSlugScheduleRoute: CompeteSlugScheduleRoute,
  CompeteSlugVolunteerRoute: CompeteSlugVolunteerRoute,
  CompeteSlugWorkoutsRoute: CompeteSlugWorkoutsRoute,
  CompeteSlugIndexRoute: CompeteSlugIndexRoute,
}

const CompeteSlugRouteWithChildren = CompeteSlugRoute._addFileChildren(
  CompeteSlugRouteChildren,
)

interface CompeteOrganizerCompetitionIdRouteChildren {
  CompeteOrganizerCompetitionIdAthletesRoute: typeof CompeteOrganizerCompetitionIdAthletesRoute
  CompeteOrganizerCompetitionIdDivisionsRoute: typeof CompeteOrganizerCompetitionIdDivisionsRoute
  CompeteOrganizerCompetitionIdPricingRoute: typeof CompeteOrganizerCompetitionIdPricingRoute
  CompeteOrganizerCompetitionIdResultsRoute: typeof CompeteOrganizerCompetitionIdResultsRoute
  CompeteOrganizerCompetitionIdRevenueRoute: typeof CompeteOrganizerCompetitionIdRevenueRoute
  CompeteOrganizerCompetitionIdScheduleRoute: typeof CompeteOrganizerCompetitionIdScheduleRoute
  CompeteOrganizerCompetitionIdSponsorsRoute: typeof CompeteOrganizerCompetitionIdSponsorsRoute
  CompeteOrganizerCompetitionIdVolunteersRoute: typeof CompeteOrganizerCompetitionIdVolunteersRoute
  CompeteOrganizerCompetitionIdIndexRoute: typeof CompeteOrganizerCompetitionIdIndexRoute
  CompeteOrganizerCompetitionIdEventsEventIdRoute: typeof CompeteOrganizerCompetitionIdEventsEventIdRoute
  CompeteOrganizerCompetitionIdEventsIndexRoute: typeof CompeteOrganizerCompetitionIdEventsIndexRoute
}

const CompeteOrganizerCompetitionIdRouteChildren: CompeteOrganizerCompetitionIdRouteChildren =
  {
    CompeteOrganizerCompetitionIdAthletesRoute:
      CompeteOrganizerCompetitionIdAthletesRoute,
    CompeteOrganizerCompetitionIdDivisionsRoute:
      CompeteOrganizerCompetitionIdDivisionsRoute,
    CompeteOrganizerCompetitionIdPricingRoute:
      CompeteOrganizerCompetitionIdPricingRoute,
    CompeteOrganizerCompetitionIdResultsRoute:
      CompeteOrganizerCompetitionIdResultsRoute,
    CompeteOrganizerCompetitionIdRevenueRoute:
      CompeteOrganizerCompetitionIdRevenueRoute,
    CompeteOrganizerCompetitionIdScheduleRoute:
      CompeteOrganizerCompetitionIdScheduleRoute,
    CompeteOrganizerCompetitionIdSponsorsRoute:
      CompeteOrganizerCompetitionIdSponsorsRoute,
    CompeteOrganizerCompetitionIdVolunteersRoute:
      CompeteOrganizerCompetitionIdVolunteersRoute,
    CompeteOrganizerCompetitionIdIndexRoute:
      CompeteOrganizerCompetitionIdIndexRoute,
    CompeteOrganizerCompetitionIdEventsEventIdRoute:
      CompeteOrganizerCompetitionIdEventsEventIdRoute,
    CompeteOrganizerCompetitionIdEventsIndexRoute:
      CompeteOrganizerCompetitionIdEventsIndexRoute,
  }

const CompeteOrganizerCompetitionIdRouteWithChildren =
  CompeteOrganizerCompetitionIdRoute._addFileChildren(
    CompeteOrganizerCompetitionIdRouteChildren,
  )

interface CompeteOrganizerSeriesGroupIdRouteChildren {
  CompeteOrganizerSeriesGroupIdEditRoute: typeof CompeteOrganizerSeriesGroupIdEditRoute
  CompeteOrganizerSeriesGroupIdIndexRoute: typeof CompeteOrganizerSeriesGroupIdIndexRoute
}

const CompeteOrganizerSeriesGroupIdRouteChildren: CompeteOrganizerSeriesGroupIdRouteChildren =
  {
    CompeteOrganizerSeriesGroupIdEditRoute:
      CompeteOrganizerSeriesGroupIdEditRoute,
    CompeteOrganizerSeriesGroupIdIndexRoute:
      CompeteOrganizerSeriesGroupIdIndexRoute,
  }

const CompeteOrganizerSeriesGroupIdRouteWithChildren =
  CompeteOrganizerSeriesGroupIdRoute._addFileChildren(
    CompeteOrganizerSeriesGroupIdRouteChildren,
  )

interface CompeteOrganizerRouteChildren {
  CompeteOrganizerCompetitionIdRoute: typeof CompeteOrganizerCompetitionIdRouteWithChildren
  CompeteOrganizerNewRoute: typeof CompeteOrganizerNewRoute
  CompeteOrganizerIndexRoute: typeof CompeteOrganizerIndexRoute
  CompeteOrganizerSeriesGroupIdRoute: typeof CompeteOrganizerSeriesGroupIdRouteWithChildren
  CompeteOrganizerSeriesNewRoute: typeof CompeteOrganizerSeriesNewRoute
  CompeteOrganizerSeriesIndexRoute: typeof CompeteOrganizerSeriesIndexRoute
}

const CompeteOrganizerRouteChildren: CompeteOrganizerRouteChildren = {
  CompeteOrganizerCompetitionIdRoute:
    CompeteOrganizerCompetitionIdRouteWithChildren,
  CompeteOrganizerNewRoute: CompeteOrganizerNewRoute,
  CompeteOrganizerIndexRoute: CompeteOrganizerIndexRoute,
  CompeteOrganizerSeriesGroupIdRoute:
    CompeteOrganizerSeriesGroupIdRouteWithChildren,
  CompeteOrganizerSeriesNewRoute: CompeteOrganizerSeriesNewRoute,
  CompeteOrganizerSeriesIndexRoute: CompeteOrganizerSeriesIndexRoute,
}

const CompeteOrganizerRouteWithChildren =
  CompeteOrganizerRoute._addFileChildren(CompeteOrganizerRouteChildren)

interface CompeteRouteChildren {
  CompeteSlugRoute: typeof CompeteSlugRouteWithChildren
  CompeteOrganizerRoute: typeof CompeteOrganizerRouteWithChildren
  CompeteIndexRoute: typeof CompeteIndexRoute
  CompeteInviteTokenRoute: typeof CompeteInviteTokenRoute
}

const CompeteRouteChildren: CompeteRouteChildren = {
  CompeteSlugRoute: CompeteSlugRouteWithChildren,
  CompeteOrganizerRoute: CompeteOrganizerRouteWithChildren,
  CompeteIndexRoute: CompeteIndexRoute,
  CompeteInviteTokenRoute: CompeteInviteTokenRoute,
}

const CompeteRouteWithChildren =
  CompeteRoute._addFileChildren(CompeteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  CompeteRoute: CompeteRouteWithChildren,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
