packages:
  - "apps/*"
  - "packages/*"

catalog:
  zod: "^3.25.76"
  react: "^19.0.0"
  react-dom: "^19.0.0"
  "@types/react": "^19.2.7"
  "@types/react-dom": "^19.2.3"
  "@typescript/native-preview": "7.0.0-dev.20251007.1"
