packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  zod: '^3.25.76'
  react: '^19.0.0'
  react-dom: '^19.0.0'
  '@types/react': '^19.2.7'
  '@types/react-dom': '^19.2.3'
  '@typescript/native-preview': '7.0.0-dev.20251007.1'
  vitest: '^3.2.3'
  '@testing-library/react': '^16.3.0'
  '@testing-library/jest-dom': '^6.6.3'
  '@testing-library/user-event': '^14.6.1'
  jsdom: '^26.1.0'
  alchemy: '^0.82.2'
