/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedInteractionsRouteImport } from './routes/_authenticated/interactions'
import { Route as AuthenticatedGymsRouteImport } from './routes/_authenticated/gyms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as ApiCrmDocumentsRouteImport } from './routes/api/crm/documents'
import { Route as ApiCrmAgentCapabilitiesRouteImport } from './routes/api/crm/agent-capabilities'
import { Route as AuthenticatedInteractionsInteractionIdRouteImport } from './routes/_authenticated/interactions.$interactionId'
import { Route as AuthenticatedGymsGymIdRouteImport } from './routes/_authenticated/gyms.$gymId'
import { Route as AuthenticatedContactsContactIdRouteImport } from './routes/_authenticated/contacts.$contactId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInteractionsRoute =
  AuthenticatedInteractionsRouteImport.update({
    id: '/interactions',
    path: '/interactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGymsRoute = AuthenticatedGymsRouteImport.update({
  id: '/gyms',
  path: '/gyms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiCrmDocumentsRoute = ApiCrmDocumentsRouteImport.update({
  id: '/api/crm/documents',
  path: '/api/crm/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrmAgentCapabilitiesRoute = ApiCrmAgentCapabilitiesRouteImport.update({
  id: '/api/crm/agent-capabilities',
  path: '/api/crm/agent-capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInteractionsInteractionIdRoute =
  AuthenticatedInteractionsInteractionIdRouteImport.update({
    id: '/$interactionId',
    path: '/$interactionId',
    getParentRoute: () => AuthenticatedInteractionsRoute,
  } as any)
const AuthenticatedGymsGymIdRoute = AuthenticatedGymsGymIdRouteImport.update({
  id: '/$gymId',
  path: '/$gymId',
  getParentRoute: () => AuthenticatedGymsRoute,
} as any)
const AuthenticatedContactsContactIdRoute =
  AuthenticatedContactsContactIdRouteImport.update({
    id: '/$contactId',
    path: '/$contactId',
    getParentRoute: () => AuthenticatedContactsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gyms': typeof AuthenticatedGymsRouteWithChildren
  '/interactions': typeof AuthenticatedInteractionsRouteWithChildren
  '/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/gyms/$gymId': typeof AuthenticatedGymsGymIdRoute
  '/interactions/$interactionId': typeof AuthenticatedInteractionsInteractionIdRoute
  '/api/crm/agent-capabilities': typeof ApiCrmAgentCapabilitiesRoute
  '/api/crm/documents': typeof ApiCrmDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gyms': typeof AuthenticatedGymsRouteWithChildren
  '/interactions': typeof AuthenticatedInteractionsRouteWithChildren
  '/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/gyms/$gymId': typeof AuthenticatedGymsGymIdRoute
  '/interactions/$interactionId': typeof AuthenticatedInteractionsInteractionIdRoute
  '/api/crm/agent-capabilities': typeof ApiCrmAgentCapabilitiesRoute
  '/api/crm/documents': typeof ApiCrmDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gyms': typeof AuthenticatedGymsRouteWithChildren
  '/_authenticated/interactions': typeof AuthenticatedInteractionsRouteWithChildren
  '/_authenticated/contacts/$contactId': typeof AuthenticatedContactsContactIdRoute
  '/_authenticated/gyms/$gymId': typeof AuthenticatedGymsGymIdRoute
  '/_authenticated/interactions/$interactionId': typeof AuthenticatedInteractionsInteractionIdRoute
  '/api/crm/agent-capabilities': typeof ApiCrmAgentCapabilitiesRoute
  '/api/crm/documents': typeof ApiCrmDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/dashboard'
    | '/gyms'
    | '/interactions'
    | '/contacts/$contactId'
    | '/gyms/$gymId'
    | '/interactions/$interactionId'
    | '/api/crm/agent-capabilities'
    | '/api/crm/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/dashboard'
    | '/gyms'
    | '/interactions'
    | '/contacts/$contactId'
    | '/gyms/$gymId'
    | '/interactions/$interactionId'
    | '/api/crm/agent-capabilities'
    | '/api/crm/documents'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/gyms'
    | '/_authenticated/interactions'
    | '/_authenticated/contacts/$contactId'
    | '/_authenticated/gyms/$gymId'
    | '/_authenticated/interactions/$interactionId'
    | '/api/crm/agent-capabilities'
    | '/api/crm/documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiCrmAgentCapabilitiesRoute: typeof ApiCrmAgentCapabilitiesRoute
  ApiCrmDocumentsRoute: typeof ApiCrmDocumentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/interactions': {
      id: '/_authenticated/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof AuthenticatedInteractionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gyms': {
      id: '/_authenticated/gyms'
      path: '/gyms'
      fullPath: '/gyms'
      preLoaderRoute: typeof AuthenticatedGymsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/crm/documents': {
      id: '/api/crm/documents'
      path: '/api/crm/documents'
      fullPath: '/api/crm/documents'
      preLoaderRoute: typeof ApiCrmDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crm/agent-capabilities': {
      id: '/api/crm/agent-capabilities'
      path: '/api/crm/agent-capabilities'
      fullPath: '/api/crm/agent-capabilities'
      preLoaderRoute: typeof ApiCrmAgentCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/interactions/$interactionId': {
      id: '/_authenticated/interactions/$interactionId'
      path: '/$interactionId'
      fullPath: '/interactions/$interactionId'
      preLoaderRoute: typeof AuthenticatedInteractionsInteractionIdRouteImport
      parentRoute: typeof AuthenticatedInteractionsRoute
    }
    '/_authenticated/gyms/$gymId': {
      id: '/_authenticated/gyms/$gymId'
      path: '/$gymId'
      fullPath: '/gyms/$gymId'
      preLoaderRoute: typeof AuthenticatedGymsGymIdRouteImport
      parentRoute: typeof AuthenticatedGymsRoute
    }
    '/_authenticated/contacts/$contactId': {
      id: '/_authenticated/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AuthenticatedContactsContactIdRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
  }
}

interface AuthenticatedContactsRouteChildren {
  AuthenticatedContactsContactIdRoute: typeof AuthenticatedContactsContactIdRoute
}

const AuthenticatedContactsRouteChildren: AuthenticatedContactsRouteChildren = {
  AuthenticatedContactsContactIdRoute: AuthenticatedContactsContactIdRoute,
}

const AuthenticatedContactsRouteWithChildren =
  AuthenticatedContactsRoute._addFileChildren(
    AuthenticatedContactsRouteChildren,
  )

interface AuthenticatedGymsRouteChildren {
  AuthenticatedGymsGymIdRoute: typeof AuthenticatedGymsGymIdRoute
}

const AuthenticatedGymsRouteChildren: AuthenticatedGymsRouteChildren = {
  AuthenticatedGymsGymIdRoute: AuthenticatedGymsGymIdRoute,
}

const AuthenticatedGymsRouteWithChildren =
  AuthenticatedGymsRoute._addFileChildren(AuthenticatedGymsRouteChildren)

interface AuthenticatedInteractionsRouteChildren {
  AuthenticatedInteractionsInteractionIdRoute: typeof AuthenticatedInteractionsInteractionIdRoute
}

const AuthenticatedInteractionsRouteChildren: AuthenticatedInteractionsRouteChildren =
  {
    AuthenticatedInteractionsInteractionIdRoute:
      AuthenticatedInteractionsInteractionIdRoute,
  }

const AuthenticatedInteractionsRouteWithChildren =
  AuthenticatedInteractionsRoute._addFileChildren(
    AuthenticatedInteractionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGymsRoute: typeof AuthenticatedGymsRouteWithChildren
  AuthenticatedInteractionsRoute: typeof AuthenticatedInteractionsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContactsRoute: AuthenticatedContactsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGymsRoute: AuthenticatedGymsRouteWithChildren,
  AuthenticatedInteractionsRoute: AuthenticatedInteractionsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiCrmAgentCapabilitiesRoute: ApiCrmAgentCapabilitiesRoute,
  ApiCrmDocumentsRoute: ApiCrmDocumentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
