import type { Connection } from "mysql2/promise"
import { batchInsert, now } from "../helpers"

export async function seed(client: Connection): Promise<void> {
	console.log("Seeding teams...")

	const ts = now()

	await batchInsert(client, "teams", [
		{
			id: "team_cokkpu1klwo0ulfhl1iwzpvnbox1",
			name: "CrossFit Box One",
			slug: "crossfit-box-one",
			description: "Premier CrossFit gym in downtown",
			created_at: ts,
			updated_at: ts,
			update_counter: 0,
			is_personal_team: 0,
			personal_team_owner_id: null,
			current_plan_id: "pro",
			type: "gym",
			parent_organization_id: null,
		},
		{
			id: "team_homeymgym",
			name: "Home Gym Heroes",
			slug: "home-gym-heroes",
			description: "For athletes training at home",
			created_at: ts,
			updated_at: ts,
			update_counter: 0,
			is_personal_team: 0,
			personal_team_owner_id: null,
			current_plan_id: "enterprise",
			type: "gym",
			parent_organization_id: null,
		},
		{
			id: "team_personaladmin",
			name: "Admin Personal",
			slug: "admin-personal",
			description: "Personal team for admin user",
			created_at: ts,
			updated_at: ts,
			update_counter: 0,
			is_personal_team: 1,
			personal_team_owner_id: "usr_demo1admin",
			current_plan_id: "free",
			type: "personal",
			parent_organization_id: null,
		},
		{
			id: "team_personalcoach",
			name: "Coach Personal",
			slug: "coach-personal",
			description: "Personal team for coach user",
			created_at: ts,
			updated_at: ts,
			update_counter: 0,
			is_personal_team: 1,
			personal_team_owner_id: "usr_demo2coach",
			current_plan_id: "free",
			type: "personal",
			parent_organization_id: null,
		},
		{
			id: "team_personaljohn",
			name: "John Personal",
			slug: "john-personal",
			description: "Personal team for John Doe",
			created_at: ts,
			updated_at: ts,
			update_counter: 0,
			is_personal_team: 1,
			personal_team_owner_id: "usr_demo3member",
			current_plan_id: "free",
			type: "personal",
			parent_organization_id: null,
		},
		{
			id: "team_personaljane",
			name: "Jane Personal",
			slug: "jane-personal",
			description: "Personal team for Jane Smith",
			created_at: ts,
			updated_at: ts,
			update_counter: 0,
			is_personal_team: 1,
			personal_team_owner_id: "usr_demo4member",
			current_plan_id: "free",
			type: "personal",
			parent_organization_id: null,
		},
		// Competition event team
		{
			id: "team_winter_throwdown_2025",
			name: "Winter Throwdown 2025",
			slug: "winter-throwdown-2025",
			description: "Competition event team for Winter Throwdown 2025",
			created_at: ts,
			updated_at: ts,
			update_counter: 0,
			is_personal_team: 0,
			personal_team_owner_id: null,
			current_plan_id: null,
			type: "competition_event",
			parent_organization_id: "team_cokkpu1klwo0ulfhl1iwzpvnbox1",
		},
		// CrossFit team
		{
			id: "team_cokkpu1klwo0ulfhl1iwzpvn",
			name: "CrossFit",
			slug: "crossfit",
			description: "Official CrossFit benchmark workouts and programming",
			created_at: ts,
			updated_at: ts,
			update_counter: 0,
			is_personal_team: 0,
			personal_team_owner_id: null,
			credit_balance: 500,
			current_plan_id: "free",
			type: "gym",
			parent_organization_id: null,
		},
		// Online competition team
		{
			id: "team_online_qualifier_2026",
			name: "Online Qualifier 2026 Athletes",
			slug: "online-qualifier-2026-athletes",
			type: "competition_event",
			description: "Athlete team for the Online Qualifier 2026",
			created_at: ts,
			updated_at: ts,
			update_counter: 0,
			is_personal_team: 0,
			personal_team_owner_id: null,
			current_plan_id: null,
			parent_organization_id: null,
		},
	])
}
