// @lat: [[crew#Role And Shift Templates]]
import { VOLUNTEER_ROLE_TYPES } from "../../../db/schemas/volunteers"
import type { CrewRoleShiftTemplate } from "./types"

export const builtInCrewRoleShiftTemplates = [
  {
    id: "one_day-local-competition",
    name: "One-day local competition",
    description:
      "Compact staffing pattern for a single-day event with one floor and a basic volunteer desk.",
    source: "built_in",
    roles: [
      {
        roleType: VOLUNTEER_ROLE_TYPES.FLOOR_MANAGER,
        targetCount: 1,
        notes: "Owns floor timing, lane readiness, and volunteer escalation.",
      },
      {
        roleType: VOLUNTEER_ROLE_TYPES.JUDGE,
        targetCount: 8,
        notes: "Tune count to lane capacity and heat schedule.",
      },
      {
        roleType: VOLUNTEER_ROLE_TYPES.CHECK_IN,
        targetCount: 2,
        notes: "Athlete and volunteer check-in during arrival window.",
      },
      {
        roleType: VOLUNTEER_ROLE_TYPES.EQUIPMENT,
        targetCount: 2,
        notes: "Handles floor reset and equipment movement.",
      },
      {
        roleType: VOLUNTEER_ROLE_TYPES.SCOREKEEPER,
        targetCount: 1,
        notes: "Keeps score intake moving during heats.",
      },
    ],
    shifts: [
      {
        key: "check-in-morning",
        name: "Morning check-in",
        roleType: VOLUNTEER_ROLE_TYPES.CHECK_IN,
        dayOffset: 0,
        startTime: "07:00",
        endTime: "09:30",
        capacity: 2,
        location: "Front desk",
        notes: "Athlete packets, volunteer arrival, and day-of questions.",
      },
      {
        key: "floor-lead",
        name: "Floor lead",
        roleType: VOLUNTEER_ROLE_TYPES.FLOOR_MANAGER,
        dayOffset: 0,
        startTime: "07:30",
        endTime: "16:30",
        capacity: 1,
        location: "Competition floor",
        notes: "Primary floor contact for heat timing and reset calls.",
      },
      {
        key: "morning-judges",
        name: "Morning judges",
        roleType: VOLUNTEER_ROLE_TYPES.JUDGE,
        dayOffset: 0,
        startTime: "08:00",
        endTime: "12:00",
        capacity: 8,
        location: "Competition floor",
        notes: "Adjust capacity to lane count before publishing assignments.",
      },
      {
        key: "afternoon-judges",
        name: "Afternoon judges",
        roleType: VOLUNTEER_ROLE_TYPES.JUDGE,
        dayOffset: 0,
        startTime: "12:00",
        endTime: "16:00",
        capacity: 8,
        location: "Competition floor",
        notes: "Adjust capacity to lane count before publishing assignments.",
      },
      {
        key: "equipment-reset",
        name: "Equipment reset",
        roleType: VOLUNTEER_ROLE_TYPES.EQUIPMENT,
        dayOffset: 0,
        startTime: "08:00",
        endTime: "16:00",
        capacity: 2,
        location: "Equipment staging",
        notes: "Stage workout transitions and support floor lead.",
      },
      {
        key: "score-table",
        name: "Score table",
        roleType: VOLUNTEER_ROLE_TYPES.SCOREKEEPER,
        dayOffset: 0,
        startTime: "08:00",
        endTime: "16:30",
        capacity: 1,
        location: "Score table",
        notes: "Collect scorecards and monitor missing scores.",
      },
    ],
    staffingAssumptions:
      "One-day local competition template: one floor lead, two judge blocks sized to lane count, check-in during arrivals, equipment reset all day, and one score-table owner.",
  },
  {
    id: "two_day-competition",
    name: "Two-day competition",
    description:
      "Two-day event template with day-specific check-in, judging, floor, equipment, and scoring coverage.",
    source: "built_in",
    roles: [
      {
        roleType: VOLUNTEER_ROLE_TYPES.FLOOR_MANAGER,
        targetCount: 2,
        notes:
          "One floor lead per day, or one lead with a backup for long days.",
      },
      {
        roleType: VOLUNTEER_ROLE_TYPES.JUDGE,
        targetCount: 16,
        notes:
          "Split by day and lane capacity; use rotations for heat-level judge details.",
      },
      {
        roleType: VOLUNTEER_ROLE_TYPES.CHECK_IN,
        targetCount: 3,
        notes: "Heavier check-in on day one, light support on day two.",
      },
      {
        roleType: VOLUNTEER_ROLE_TYPES.EQUIPMENT,
        targetCount: 4,
        notes: "Reset crew for each day and teardown support after finals.",
      },
      {
        roleType: VOLUNTEER_ROLE_TYPES.SCOREKEEPER,
        targetCount: 2,
        notes: "Score intake coverage across both days.",
      },
      {
        roleType: VOLUNTEER_ROLE_TYPES.MEDICAL,
        targetCount: 1,
        notes: "Named medical contact available both days.",
      },
    ],
    shifts: [
      {
        key: "day-1-check-in",
        name: "Day 1 check-in",
        roleType: VOLUNTEER_ROLE_TYPES.CHECK_IN,
        dayOffset: 0,
        startTime: "07:00",
        endTime: "10:00",
        capacity: 3,
        location: "Front desk",
      },
      {
        key: "day-1-floor-lead",
        name: "Day 1 floor lead",
        roleType: VOLUNTEER_ROLE_TYPES.FLOOR_MANAGER,
        dayOffset: 0,
        startTime: "07:30",
        endTime: "17:00",
        capacity: 1,
        location: "Competition floor",
      },
      {
        key: "day-1-judges",
        name: "Day 1 judges",
        roleType: VOLUNTEER_ROLE_TYPES.JUDGE,
        dayOffset: 0,
        startTime: "08:00",
        endTime: "17:00",
        capacity: 8,
        location: "Competition floor",
      },
      {
        key: "day-1-equipment",
        name: "Day 1 equipment reset",
        roleType: VOLUNTEER_ROLE_TYPES.EQUIPMENT,
        dayOffset: 0,
        startTime: "08:00",
        endTime: "17:00",
        capacity: 2,
        location: "Equipment staging",
      },
      {
        key: "day-1-score-table",
        name: "Day 1 score table",
        roleType: VOLUNTEER_ROLE_TYPES.SCOREKEEPER,
        dayOffset: 0,
        startTime: "08:00",
        endTime: "17:30",
        capacity: 1,
        location: "Score table",
      },
      {
        key: "day-2-check-in",
        name: "Day 2 check-in",
        roleType: VOLUNTEER_ROLE_TYPES.CHECK_IN,
        dayOffset: 1,
        startTime: "07:30",
        endTime: "09:00",
        capacity: 1,
        location: "Front desk",
      },
      {
        key: "day-2-floor-lead",
        name: "Day 2 floor lead",
        roleType: VOLUNTEER_ROLE_TYPES.FLOOR_MANAGER,
        dayOffset: 1,
        startTime: "07:30",
        endTime: "16:00",
        capacity: 1,
        location: "Competition floor",
      },
      {
        key: "day-2-judges",
        name: "Day 2 judges",
        roleType: VOLUNTEER_ROLE_TYPES.JUDGE,
        dayOffset: 1,
        startTime: "08:00",
        endTime: "16:00",
        capacity: 8,
        location: "Competition floor",
      },
      {
        key: "day-2-equipment",
        name: "Day 2 equipment and teardown",
        roleType: VOLUNTEER_ROLE_TYPES.EQUIPMENT,
        dayOffset: 1,
        startTime: "08:00",
        endTime: "17:00",
        capacity: 2,
        location: "Equipment staging",
      },
      {
        key: "day-2-score-table",
        name: "Day 2 score table",
        roleType: VOLUNTEER_ROLE_TYPES.SCOREKEEPER,
        dayOffset: 1,
        startTime: "08:00",
        endTime: "16:30",
        capacity: 1,
        location: "Score table",
      },
      {
        key: "medical-coverage",
        name: "Medical coverage",
        roleType: VOLUNTEER_ROLE_TYPES.MEDICAL,
        dayOffset: 0,
        startTime: "08:00",
        endTime: "17:00",
        capacity: 1,
        location: "Medical station",
        notes:
          "Duplicate manually for day two if the same person cannot cover both days.",
      },
    ],
    staffingAssumptions:
      "Two-day competition template: day-level floor leads, judge coverage sized to lane count, heavier day-one check-in, reset crew both days, score-table coverage both days, and explicit medical coverage.",
  },
  {
    id: "online-qualifier-support",
    name: "Online qualifier support",
    description:
      "Light operational coverage for online qualifier score review and organizer support.",
    source: "built_in",
    roles: [
      {
        roleType: VOLUNTEER_ROLE_TYPES.SCOREKEEPER,
        targetCount: 2,
        notes: "Review score submissions and chase missing videos.",
      },
      {
        roleType: VOLUNTEER_ROLE_TYPES.STAFF,
        targetCount: 1,
        notes: "Organizer support and escalation owner.",
      },
      {
        roleType: VOLUNTEER_ROLE_TYPES.MEDIA,
        targetCount: 1,
        notes: "Publishes deadline reminders and leaderboard updates.",
      },
    ],
    shifts: [
      {
        key: "submission-review",
        name: "Submission review",
        roleType: VOLUNTEER_ROLE_TYPES.SCOREKEEPER,
        dayOffset: 0,
        startTime: "09:00",
        endTime: "12:00",
        capacity: 2,
        location: "Remote",
        notes: "Review pending scores and video links.",
      },
      {
        key: "organizer-support",
        name: "Organizer support",
        roleType: VOLUNTEER_ROLE_TYPES.STAFF,
        dayOffset: 0,
        startTime: "09:00",
        endTime: "17:00",
        capacity: 1,
        location: "Remote",
      },
      {
        key: "deadline-updates",
        name: "Deadline updates",
        roleType: VOLUNTEER_ROLE_TYPES.MEDIA,
        dayOffset: 0,
        startTime: "15:00",
        endTime: "17:00",
        capacity: 1,
        location: "Remote",
      },
    ],
    staffingAssumptions:
      "Online qualifier support template: remote score review, a named organizer support owner, and deadline communications coverage.",
  },
] satisfies CrewRoleShiftTemplate[]

export function getBuiltInCrewRoleShiftTemplate(templateId: string) {
  return (
    builtInCrewRoleShiftTemplates.find(
      (template) => template.id === templateId,
    ) ?? null
  )
}
