/**
 * Cloudflare environment bindings type declaration.
 *
 * This extends the CloudflareEnv interface with types inferred from Alchemy.
 * The Env type is exported from alchemy.run.ts based on the infrastructure configuration.
 *
 * Note: The existing worker-configuration.d.ts (generated by wrangler) provides
 * the current bindings. When fully migrating to Alchemy, import Env from alchemy.run.ts
 * and use: declare global { interface CloudflareEnv extends Env {} }
 */
import type { Env } from "../../alchemy.run"

declare global {
  interface CloudflareEnv extends Env {}
  namespace Cloudflare {
    // Augment the wrangler-generated Env with bindings declared in alchemy.run.ts
    // that aren't included in `wrangler types` output (Durable Objects, AI, etc.).
    interface Env {
      JUDGE_SCHEDULER_AGENT: DurableObjectNamespace
      AI: Ai
      /** Cloudflare account id — routed through AI Gateway by the agents */
      CF_ACCOUNT_ID: string
      /** AI Gateway name from alchemy.run.ts */
      CF_AIG_GATEWAY: string
      /** API token with AI Gateway permission */
      CF_AIG_TOKEN: string
    }
  }
}
