/**
 * Cloudflare environment bindings type declaration.
 *
 * This extends the CloudflareEnv interface with types inferred from Alchemy.
 * The Env type is exported from alchemy.run.ts based on the infrastructure configuration.
 *
 * Note: The existing worker-configuration.d.ts (generated by wrangler) provides
 * the current bindings. When fully migrating to Alchemy, import Env from alchemy.run.ts
 * and use: declare global { interface CloudflareEnv extends Env {} }
 */
import type { Env } from "../../alchemy.run"

declare global {
	interface CloudflareEnv extends Env {}
}

export {}
