import Database from "better-sqlite3"
import { drizzle, type BetterSQLite3Database } from "drizzle-orm/better-sqlite3"
import * as fs from "node:fs"
import * as path from "node:path"
import * as schema from "@/db/schema"

/**
 * Path to the exported schema SQL file.
 *
 * This file is generated by `pnpm drizzle-kit export --sql > test/lib/schema.sql`
 * and avoids D1-specific migration syntax issues with better-sqlite3.
 *
 * IMPORTANT: Regenerate this file after schema changes!
 * Run: cd apps/wodsmith && pnpm drizzle-kit export --sql > test/lib/schema.sql
 */
const SCHEMA_SQL_PATH = path.join(__dirname, "schema.sql")

/**
 * Creates an in-memory SQLite database with schema applied.
 * Uses drizzle-kit export SQL for compatibility with better-sqlite3.
 */
export function createTestDb() {
	const sqlite = new Database(":memory:")

	// Enable foreign keys (disabled by default in SQLite)
	sqlite.pragma("foreign_keys = OFF") // Temporarily off during schema creation

	// Apply schema from exported SQL
	applySchema(sqlite)

	// Re-enable foreign keys
	sqlite.pragma("foreign_keys = ON")

	const db = drizzle(sqlite, { schema })

	return { db, sqlite }
}

/**
 * Clean up the test database
 */
export function cleanupTestDb(sqlite: Database.Database) {
	sqlite.close()
}

/**
 * Apply schema SQL to create all tables
 */
function applySchema(sqlite: Database.Database) {
	const sqlContent = fs.readFileSync(SCHEMA_SQL_PATH, "utf-8")

	// Split by semicolons to get individual statements
	// Filter out empty statements
	const statements = sqlContent
		.split(/;\s*\n/)
		.map((s) => s.trim())
		.filter((s) => s.length > 0 && !s.startsWith("--"))

	for (const statement of statements) {
		try {
			sqlite.exec(statement + ";")
		} catch {
			// Silently ignore errors (e.g., duplicate indexes)
			// Uncomment for debugging:
			// console.error(`Schema error: ${(error as Error).message}`)
		}
	}
}

export type TestDb = BetterSQLite3Database<typeof schema>
