/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f1bac578f8878aca08de5e3cd5433284)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index")
  }
  interface Env {
    AGENT_AUTH_ORIGIN: "https://localhost:3000"
    AGENT_RESOURCE: "https://localhost:8791/mcp"
    TRAINING: Service /* entrypoint AgentTrainingService from wodsmith-start */
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, "AGENT_AUTH_ORIGIN" | "AGENT_RESOURCE">
    > {}
}
