import { PAGE_COVERAGE_VERSION } from "./config.mjs"

export function summarizeLedger(records) {
  const countBy = (field) =>
    Object.fromEntries(
      [...new Set(records.map((record) => record[field]))]
        .sort()
        .map((value) => [value, records.filter((record) => record[field] === value).length]),
    )
  return {
    total: records.length,
    browser: records.filter((record) => ["page", "page-layout"].includes(record.kind))
      .length,
    nonPage: records.filter((record) => !["page", "page-layout"].includes(record.kind))
      .length,
    byApp: countBy("app"),
    byKind: countBy("kind"),
    byDisposition: countBy("disposition"),
    byScenarioStatus: Object.fromEntries(
      ["blocked", "pending", "verified"].map((status) => [
        status,
        records.flatMap((record) => record.scenarios).filter((scenario) => scenario.status === status)
          .length,
      ]),
    ),
  }
}

export function renderLedgerJson(records) {
  return `${JSON.stringify(
    {
      version: PAGE_COVERAGE_VERSION,
      generatedFrom: "docs/ui-library/page-coverage.plan.json",
      summary: summarizeLedger(records),
      records,
    },
    null,
    2,
  )}\n`
}

function escapeCell(value) {
  if (value === null || value === undefined || value === "") return "—"
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ")
}

export function renderLedgerMarkdown(records) {
  const summary = summarizeLedger(records)
  const rows = records.map(
    (record) =>
      `| \`${escapeCell(record.routeId)}\` | ${escapeCell(record.app)} | ${escapeCell(record.kind)} | ${escapeCell(record.disposition)} | \`${escapeCell(record.urlPattern)}\` | ${record.scenarios.length} |`,
  )
  return `# WODsmith page coverage ledger

This generated ledger joins authoritative route, documentation, and service discovery with the human coverage plan. Edit the plan, then regenerate; do not edit this file directly.

Regenerate with \`pnpm page-coverage:generate\` and verify it with \`pnpm check:page-coverage\`.

## Reconciled baseline

The repository currently contains **${summary.total} records**: **${summary.browser} browser page/page-layout records** and **${summary.nonPage} explicit non-page decisions**.

The ${summary.browser} visual records plus ${summary.byKind.redirect ?? 0} redirect-only records reconcile to ${summary.browser + (summary.byKind.redirect ?? 0)} browser-addressable TanStack/Docs patterns. The earlier ~203 estimate incorrectly treated many trailing-slash index pages as layout-only; source declarations classify those index records as pages.

| App | Records |
| --- | ---: |
${Object.entries(summary.byApp)
  .map(([app, count]) => `| ${app} | ${count} |`)
  .join("\n")}

| Kind | Records |
| --- | ---: |
${Object.entries(summary.byKind)
  .map(([kind, count]) => `| ${kind} | ${count} |`)
  .join("\n")}

## Joined records

| Route ID | App | Kind | Disposition | URL pattern | Scenarios |
| --- | --- | --- | --- | --- | ---: |
${rows.join("\n")}
`
}
